/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fl.uploadfile.model.impl;

import com.fl.uploadfile.model.UploadFile;
import com.fl.uploadfile.model.UploadFileModel;
import com.fl.uploadfile.model.UploadFileSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UploadFile service. Represents a row in the &quot;flaskupload_UploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fl.uploadfile.model.UploadFileModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UploadFileImpl}.
 * </p>
 *
 * @author Rumba Solutions
 * @see UploadFileImpl
 * @see com.fl.uploadfile.model.UploadFile
 * @see com.fl.uploadfile.model.UploadFileModel
 * @generated
 */
@JSON(strict = true)
public class UploadFileModelImpl extends BaseModelImpl<UploadFile>
	implements UploadFileModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a upload file model instance should use the {@link com.fl.uploadfile.model.UploadFile} interface instead.
	 */
	public static final String TABLE_NAME = "flaskupload_UploadFile";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fileUploadId", Types.BIGINT },
			{ "fileEntryId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "size_", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table flaskupload_UploadFile (fileUploadId LONG not null primary key,fileEntryId LONG,title VARCHAR(75) null,description VARCHAR(75) null,size_ LONG)";
	public static final String TABLE_SQL_DROP = "drop table flaskupload_UploadFile";
	public static final String ORDER_BY_JPQL = " ORDER BY uploadFile.title ASC";
	public static final String ORDER_BY_SQL = " ORDER BY flaskupload_UploadFile.title ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fl.uploadfile.model.UploadFile"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fl.uploadfile.model.UploadFile"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UploadFile toModel(UploadFileSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UploadFile model = new UploadFileImpl();

		model.setFileUploadId(soapModel.getFileUploadId());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setSize(soapModel.getSize());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UploadFile> toModels(UploadFileSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UploadFile> models = new ArrayList<UploadFile>(soapModels.length);

		for (UploadFileSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fl.uploadfile.model.UploadFile"));

	public UploadFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileUploadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileUploadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileUploadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UploadFile.class;
	}

	@Override
	public String getModelClassName() {
		return UploadFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fileUploadId", getFileUploadId());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("title", getTitle());
		attributes.put("description", getDescription());
		attributes.put("size", getSize());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fileUploadId = (Long)attributes.get("fileUploadId");

		if (fileUploadId != null) {
			setFileUploadId(fileUploadId);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long size = (Long)attributes.get("size");

		if (size != null) {
			setSize(size);
		}
	}

	@JSON
	@Override
	public long getFileUploadId() {
		return _fileUploadId;
	}

	@Override
	public void setFileUploadId(long fileUploadId) {
		_fileUploadId = fileUploadId;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public long getSize() {
		return _size;
	}

	@Override
	public void setSize(long size) {
		_size = size;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			UploadFile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UploadFile toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UploadFile)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UploadFileImpl uploadFileImpl = new UploadFileImpl();

		uploadFileImpl.setFileUploadId(getFileUploadId());
		uploadFileImpl.setFileEntryId(getFileEntryId());
		uploadFileImpl.setTitle(getTitle());
		uploadFileImpl.setDescription(getDescription());
		uploadFileImpl.setSize(getSize());

		uploadFileImpl.resetOriginalValues();

		return uploadFileImpl;
	}

	@Override
	public int compareTo(UploadFile uploadFile) {
		int value = 0;

		value = getTitle().compareTo(uploadFile.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UploadFile)) {
			return false;
		}

		UploadFile uploadFile = (UploadFile)obj;

		long primaryKey = uploadFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UploadFile> toCacheModel() {
		UploadFileCacheModel uploadFileCacheModel = new UploadFileCacheModel();

		uploadFileCacheModel.fileUploadId = getFileUploadId();

		uploadFileCacheModel.fileEntryId = getFileEntryId();

		uploadFileCacheModel.title = getTitle();

		String title = uploadFileCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			uploadFileCacheModel.title = null;
		}

		uploadFileCacheModel.description = getDescription();

		String description = uploadFileCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			uploadFileCacheModel.description = null;
		}

		uploadFileCacheModel.size = getSize();

		return uploadFileCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{fileUploadId=");
		sb.append(getFileUploadId());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", size=");
		sb.append(getSize());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.fl.uploadfile.model.UploadFile");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fileUploadId</column-name><column-value><![CDATA[");
		sb.append(getFileUploadId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>size</column-name><column-value><![CDATA[");
		sb.append(getSize());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UploadFile.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UploadFile.class
		};
	private long _fileUploadId;
	private long _fileEntryId;
	private String _title;
	private String _description;
	private long _size;
	private UploadFile _escapedModel;
}