/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EventType service. Represents a row in the &quot;flaskevents_EventType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.EventTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.EventTypeImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see EventType
 * @see com.rumbasolutions.flask.model.impl.EventTypeImpl
 * @see com.rumbasolutions.flask.model.impl.EventTypeModelImpl
 * @generated
 */
public interface EventTypeModel extends BaseModel<EventType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event type model instance should use the {@link EventType} interface instead.
	 */

	/**
	 * Returns the primary key of this event type.
	 *
	 * @return the primary key of this event type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event type.
	 *
	 * @param primaryKey the primary key of this event type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event type ID of this event type.
	 *
	 * @return the event type ID of this event type
	 */
	public long getEventTypeId();

	/**
	 * Sets the event type ID of this event type.
	 *
	 * @param eventTypeId the event type ID of this event type
	 */
	public void setEventTypeId(long eventTypeId);

	/**
	 * Returns the event type key of this event type.
	 *
	 * @return the event type key of this event type
	 */
	@AutoEscape
	public String getEventTypeKey();

	/**
	 * Sets the event type key of this event type.
	 *
	 * @param eventTypeKey the event type key of this event type
	 */
	public void setEventTypeKey(String eventTypeKey);

	/**
	 * Returns the event type name of this event type.
	 *
	 * @return the event type name of this event type
	 */
	@AutoEscape
	public String getEventTypeName();

	/**
	 * Sets the event type name of this event type.
	 *
	 * @param eventTypeName the event type name of this event type
	 */
	public void setEventTypeName(String eventTypeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.EventType eventType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.EventType> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.EventType toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.EventType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}