/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the EventSubDetail service. Represents a row in the &quot;flaskevents_EventSubDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.EventSubDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.EventSubDetailImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see EventSubDetail
 * @see com.rumbasolutions.flask.model.impl.EventSubDetailImpl
 * @see com.rumbasolutions.flask.model.impl.EventSubDetailModelImpl
 * @generated
 */
public interface EventSubDetailModel extends BaseModel<EventSubDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event sub detail model instance should use the {@link EventSubDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this event sub detail.
	 *
	 * @return the primary key of this event sub detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event sub detail.
	 *
	 * @param primaryKey the primary key of this event sub detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event sub detail ID of this event sub detail.
	 *
	 * @return the event sub detail ID of this event sub detail
	 */
	public long getEventSubDetailId();

	/**
	 * Sets the event sub detail ID of this event sub detail.
	 *
	 * @param eventSubDetailId the event sub detail ID of this event sub detail
	 */
	public void setEventSubDetailId(long eventSubDetailId);

	/**
	 * Returns the event detail ID of this event sub detail.
	 *
	 * @return the event detail ID of this event sub detail
	 */
	public long getEventDetailId();

	/**
	 * Sets the event detail ID of this event sub detail.
	 *
	 * @param eventDetailId the event detail ID of this event sub detail
	 */
	public void setEventDetailId(long eventDetailId);

	/**
	 * Returns the event sub detail title of this event sub detail.
	 *
	 * @return the event sub detail title of this event sub detail
	 */
	@AutoEscape
	public String getEventSubDetailTitle();

	/**
	 * Sets the event sub detail title of this event sub detail.
	 *
	 * @param eventSubDetailTitle the event sub detail title of this event sub detail
	 */
	public void setEventSubDetailTitle(String eventSubDetailTitle);

	/**
	 * Returns the event sub detail desc of this event sub detail.
	 *
	 * @return the event sub detail desc of this event sub detail
	 */
	@AutoEscape
	public String getEventSubDetailDesc();

	/**
	 * Sets the event sub detail desc of this event sub detail.
	 *
	 * @param eventSubDetailDesc the event sub detail desc of this event sub detail
	 */
	public void setEventSubDetailDesc(String eventSubDetailDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.EventSubDetail eventSubDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.EventSubDetail> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.EventSubDetail toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.EventSubDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}