/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventDetailImage service. Represents a row in the &quot;flaskevents_EventDetailImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.EventDetailImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.EventDetailImageImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see EventDetailImage
 * @see com.rumbasolutions.flask.model.impl.EventDetailImageImpl
 * @see com.rumbasolutions.flask.model.impl.EventDetailImageModelImpl
 * @generated
 */
public interface EventDetailImageModel extends BaseModel<EventDetailImage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event detail image model instance should use the {@link EventDetailImage} interface instead.
	 */

	/**
	 * Returns the primary key of this event detail image.
	 *
	 * @return the primary key of this event detail image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event detail image.
	 *
	 * @param primaryKey the primary key of this event detail image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event detail image ID of this event detail image.
	 *
	 * @return the event detail image ID of this event detail image
	 */
	public long getEventDetailImageId();

	/**
	 * Sets the event detail image ID of this event detail image.
	 *
	 * @param eventDetailImageId the event detail image ID of this event detail image
	 */
	public void setEventDetailImageId(long eventDetailImageId);

	/**
	 * Returns the company ID of this event detail image.
	 *
	 * @return the company ID of this event detail image
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this event detail image.
	 *
	 * @param companyId the company ID of this event detail image
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event detail image.
	 *
	 * @return the user ID of this event detail image
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this event detail image.
	 *
	 * @param userId the user ID of this event detail image
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event detail image.
	 *
	 * @return the user uuid of this event detail image
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this event detail image.
	 *
	 * @param userUuid the user uuid of this event detail image
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this event detail image.
	 *
	 * @return the created date of this event detail image
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this event detail image.
	 *
	 * @param createdDate the created date of this event detail image
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this event detail image.
	 *
	 * @return the modified date of this event detail image
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this event detail image.
	 *
	 * @param modifiedDate the modified date of this event detail image
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event detail ID of this event detail image.
	 *
	 * @return the event detail ID of this event detail image
	 */
	public long getEventDetailId();

	/**
	 * Sets the event detail ID of this event detail image.
	 *
	 * @param eventDetailId the event detail ID of this event detail image
	 */
	public void setEventDetailId(long eventDetailId);

	/**
	 * Returns the imagetitle of this event detail image.
	 *
	 * @return the imagetitle of this event detail image
	 */
	@AutoEscape
	public String getImagetitle();

	/**
	 * Sets the imagetitle of this event detail image.
	 *
	 * @param imagetitle the imagetitle of this event detail image
	 */
	public void setImagetitle(String imagetitle);

	/**
	 * Returns the image desc of this event detail image.
	 *
	 * @return the image desc of this event detail image
	 */
	@AutoEscape
	public String getImageDesc();

	/**
	 * Sets the image desc of this event detail image.
	 *
	 * @param imageDesc the image desc of this event detail image
	 */
	public void setImageDesc(String imageDesc);

	/**
	 * Returns the image path of this event detail image.
	 *
	 * @return the image path of this event detail image
	 */
	@AutoEscape
	public String getImagePath();

	/**
	 * Sets the image path of this event detail image.
	 *
	 * @param imagePath the image path of this event detail image
	 */
	public void setImagePath(String imagePath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.EventDetailImage eventDetailImage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.EventDetailImage> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.EventDetailImage toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.EventDetailImage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}