/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventDetail service. Represents a row in the &quot;flaskevents_EventDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.EventDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.EventDetailImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see EventDetail
 * @see com.rumbasolutions.flask.model.impl.EventDetailImpl
 * @see com.rumbasolutions.flask.model.impl.EventDetailModelImpl
 * @generated
 */
public interface EventDetailModel extends BaseModel<EventDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event detail model instance should use the {@link EventDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this event detail.
	 *
	 * @return the primary key of this event detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event detail.
	 *
	 * @param primaryKey the primary key of this event detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the event detail ID of this event detail.
	 *
	 * @return the event detail ID of this event detail
	 */
	public long getEventDetailId();

	/**
	 * Sets the event detail ID of this event detail.
	 *
	 * @param eventDetailId the event detail ID of this event detail
	 */
	public void setEventDetailId(long eventDetailId);

	/**
	 * Returns the company ID of this event detail.
	 *
	 * @return the company ID of this event detail
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this event detail.
	 *
	 * @param companyId the company ID of this event detail
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this event detail.
	 *
	 * @return the user ID of this event detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this event detail.
	 *
	 * @param userId the user ID of this event detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event detail.
	 *
	 * @return the user uuid of this event detail
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this event detail.
	 *
	 * @param userUuid the user uuid of this event detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this event detail.
	 *
	 * @return the created date of this event detail
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this event detail.
	 *
	 * @param createdDate the created date of this event detail
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this event detail.
	 *
	 * @return the modified date of this event detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this event detail.
	 *
	 * @param modifiedDate the modified date of this event detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event ID of this event detail.
	 *
	 * @return the event ID of this event detail
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event detail.
	 *
	 * @param eventId the event ID of this event detail
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the info type ID of this event detail.
	 *
	 * @return the info type ID of this event detail
	 */
	public long getInfoTypeId();

	/**
	 * Sets the info type ID of this event detail.
	 *
	 * @param infoTypeId the info type ID of this event detail
	 */
	public void setInfoTypeId(long infoTypeId);

	/**
	 * Returns the info type category ID of this event detail.
	 *
	 * @return the info type category ID of this event detail
	 */
	public long getInfoTypeCategoryId();

	/**
	 * Sets the info type category ID of this event detail.
	 *
	 * @param infoTypeCategoryId the info type category ID of this event detail
	 */
	public void setInfoTypeCategoryId(long infoTypeCategoryId);

	/**
	 * Returns the event detail info name of this event detail.
	 *
	 * @return the event detail info name of this event detail
	 */
	@AutoEscape
	public String getEventDetailInfoName();

	/**
	 * Sets the event detail info name of this event detail.
	 *
	 * @param eventDetailInfoName the event detail info name of this event detail
	 */
	public void setEventDetailInfoName(String eventDetailInfoName);

	/**
	 * Returns the event detail info desc of this event detail.
	 *
	 * @return the event detail info desc of this event detail
	 */
	@AutoEscape
	public String getEventDetailInfoDesc();

	/**
	 * Sets the event detail info desc of this event detail.
	 *
	 * @param eventDetailInfoDesc the event detail info desc of this event detail
	 */
	public void setEventDetailInfoDesc(String eventDetailInfoDesc);

	/**
	 * Returns the event detail info comment of this event detail.
	 *
	 * @return the event detail info comment of this event detail
	 */
	@AutoEscape
	public String getEventDetailInfoComment();

	/**
	 * Sets the event detail info comment of this event detail.
	 *
	 * @param eventDetailInfoComment the event detail info comment of this event detail
	 */
	public void setEventDetailInfoComment(String eventDetailInfoComment);

	/**
	 * Returns the event detail address line1 of this event detail.
	 *
	 * @return the event detail address line1 of this event detail
	 */
	@AutoEscape
	public String getEventDetailAddressLine1();

	/**
	 * Sets the event detail address line1 of this event detail.
	 *
	 * @param eventDetailAddressLine1 the event detail address line1 of this event detail
	 */
	public void setEventDetailAddressLine1(String eventDetailAddressLine1);

	/**
	 * Returns the event detail address line2 of this event detail.
	 *
	 * @return the event detail address line2 of this event detail
	 */
	@AutoEscape
	public String getEventDetailAddressLine2();

	/**
	 * Sets the event detail address line2 of this event detail.
	 *
	 * @param eventDetailAddressLine2 the event detail address line2 of this event detail
	 */
	public void setEventDetailAddressLine2(String eventDetailAddressLine2);

	/**
	 * Returns the event detail infocity of this event detail.
	 *
	 * @return the event detail infocity of this event detail
	 */
	@AutoEscape
	public String getEventDetailInfocity();

	/**
	 * Sets the event detail infocity of this event detail.
	 *
	 * @param eventDetailInfocity the event detail infocity of this event detail
	 */
	public void setEventDetailInfocity(String eventDetailInfocity);

	/**
	 * Returns the event detail zip of this event detail.
	 *
	 * @return the event detail zip of this event detail
	 */
	@AutoEscape
	public String getEventDetailZip();

	/**
	 * Sets the event detail zip of this event detail.
	 *
	 * @param eventDetailZip the event detail zip of this event detail
	 */
	public void setEventDetailZip(String eventDetailZip);

	/**
	 * Returns the event detail state of this event detail.
	 *
	 * @return the event detail state of this event detail
	 */
	@AutoEscape
	public String getEventDetailState();

	/**
	 * Sets the event detail state of this event detail.
	 *
	 * @param eventDetailState the event detail state of this event detail
	 */
	public void setEventDetailState(String eventDetailState);

	/**
	 * Returns the event detail country of this event detail.
	 *
	 * @return the event detail country of this event detail
	 */
	@AutoEscape
	public String getEventDetailCountry();

	/**
	 * Sets the event detail country of this event detail.
	 *
	 * @param eventDetailCountry the event detail country of this event detail
	 */
	public void setEventDetailCountry(String eventDetailCountry);

	/**
	 * Returns the event detail latitude of this event detail.
	 *
	 * @return the event detail latitude of this event detail
	 */
	@AutoEscape
	public String getEventDetailLatitude();

	/**
	 * Sets the event detail latitude of this event detail.
	 *
	 * @param eventDetailLatitude the event detail latitude of this event detail
	 */
	public void setEventDetailLatitude(String eventDetailLatitude);

	/**
	 * Returns the event detail longitude of this event detail.
	 *
	 * @return the event detail longitude of this event detail
	 */
	@AutoEscape
	public String getEventDetailLongitude();

	/**
	 * Sets the event detail longitude of this event detail.
	 *
	 * @param eventDetailLongitude the event detail longitude of this event detail
	 */
	public void setEventDetailLongitude(String eventDetailLongitude);

	/**
	 * Returns the event detail phone of this event detail.
	 *
	 * @return the event detail phone of this event detail
	 */
	@AutoEscape
	public String getEventDetailPhone();

	/**
	 * Sets the event detail phone of this event detail.
	 *
	 * @param eventDetailPhone the event detail phone of this event detail
	 */
	public void setEventDetailPhone(String eventDetailPhone);

	/**
	 * Returns the event detail website of this event detail.
	 *
	 * @return the event detail website of this event detail
	 */
	@AutoEscape
	public String getEventDetailWebsite();

	/**
	 * Sets the event detail website of this event detail.
	 *
	 * @param eventDetailWebsite the event detail website of this event detail
	 */
	public void setEventDetailWebsite(String eventDetailWebsite);

	/**
	 * Returns the event detail cost of this event detail.
	 *
	 * @return the event detail cost of this event detail
	 */
	public double getEventDetailCost();

	/**
	 * Sets the event detail cost of this event detail.
	 *
	 * @param eventDetailCost the event detail cost of this event detail
	 */
	public void setEventDetailCost(double eventDetailCost);

	/**
	 * Returns the hours of operation of this event detail.
	 *
	 * @return the hours of operation of this event detail
	 */
	@AutoEscape
	public String getHoursOfOperation();

	/**
	 * Sets the hours of operation of this event detail.
	 *
	 * @param hoursOfOperation the hours of operation of this event detail
	 */
	public void setHoursOfOperation(String hoursOfOperation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.EventDetail eventDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.EventDetail> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.EventDetail toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.EventDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}