/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserEvent service. Represents a row in the &quot;flaskevents_UserEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.UserEventModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.UserEventImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see UserEvent
 * @see com.rumbasolutions.flask.model.impl.UserEventImpl
 * @see com.rumbasolutions.flask.model.impl.UserEventModelImpl
 * @generated
 */
public interface UserEventModel extends BaseModel<UserEvent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user event model instance should use the {@link UserEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this user event.
	 *
	 * @return the primary key of this user event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user event.
	 *
	 * @param primaryKey the primary key of this user event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user event ID of this user event.
	 *
	 * @return the user event ID of this user event
	 */
	public long getUserEventId();

	/**
	 * Sets the user event ID of this user event.
	 *
	 * @param userEventId the user event ID of this user event
	 */
	public void setUserEventId(long userEventId);

	/**
	 * Returns the user ID of this user event.
	 *
	 * @return the user ID of this user event
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user event.
	 *
	 * @param userId the user ID of this user event
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user event.
	 *
	 * @return the user uuid of this user event
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user event.
	 *
	 * @param userUuid the user uuid of this user event
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the event ID of this user event.
	 *
	 * @return the event ID of this user event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this user event.
	 *
	 * @param eventId the event ID of this user event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the created date of this user event.
	 *
	 * @return the created date of this user event
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this user event.
	 *
	 * @param createdDate the created date of this user event
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.UserEvent userEvent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.UserEvent> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.UserEvent toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.UserEvent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}