/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VenueSubDetail service. Represents a row in the &quot;flaskevents_VenueSubDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.VenueSubDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.VenueSubDetailImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see VenueSubDetail
 * @see com.rumbasolutions.flask.model.impl.VenueSubDetailImpl
 * @see com.rumbasolutions.flask.model.impl.VenueSubDetailModelImpl
 * @generated
 */
public interface VenueSubDetailModel extends BaseModel<VenueSubDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a venue sub detail model instance should use the {@link VenueSubDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this venue sub detail.
	 *
	 * @return the primary key of this venue sub detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this venue sub detail.
	 *
	 * @param primaryKey the primary key of this venue sub detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the venue sub detail ID of this venue sub detail.
	 *
	 * @return the venue sub detail ID of this venue sub detail
	 */
	public long getVenueSubDetailId();

	/**
	 * Sets the venue sub detail ID of this venue sub detail.
	 *
	 * @param venueSubDetailId the venue sub detail ID of this venue sub detail
	 */
	public void setVenueSubDetailId(long venueSubDetailId);

	/**
	 * Returns the venue detail ID of this venue sub detail.
	 *
	 * @return the venue detail ID of this venue sub detail
	 */
	public long getVenueDetailId();

	/**
	 * Sets the venue detail ID of this venue sub detail.
	 *
	 * @param venueDetailId the venue detail ID of this venue sub detail
	 */
	public void setVenueDetailId(long venueDetailId);

	/**
	 * Returns the venue sub detail title of this venue sub detail.
	 *
	 * @return the venue sub detail title of this venue sub detail
	 */
	@AutoEscape
	public String getVenueSubDetailTitle();

	/**
	 * Sets the venue sub detail title of this venue sub detail.
	 *
	 * @param venueSubDetailTitle the venue sub detail title of this venue sub detail
	 */
	public void setVenueSubDetailTitle(String venueSubDetailTitle);

	/**
	 * Returns the venue sub detail desc of this venue sub detail.
	 *
	 * @return the venue sub detail desc of this venue sub detail
	 */
	@AutoEscape
	public String getVenueSubDetailDesc();

	/**
	 * Sets the venue sub detail desc of this venue sub detail.
	 *
	 * @param venueSubDetailDesc the venue sub detail desc of this venue sub detail
	 */
	public void setVenueSubDetailDesc(String venueSubDetailDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.VenueSubDetail venueSubDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.VenueSubDetail> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.VenueSubDetail toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.VenueSubDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}