/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VenueDetail service. Represents a row in the &quot;flaskevents_VenueDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.VenueDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.VenueDetailImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see VenueDetail
 * @see com.rumbasolutions.flask.model.impl.VenueDetailImpl
 * @see com.rumbasolutions.flask.model.impl.VenueDetailModelImpl
 * @generated
 */
public interface VenueDetailModel extends BaseModel<VenueDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a venue detail model instance should use the {@link VenueDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this venue detail.
	 *
	 * @return the primary key of this venue detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this venue detail.
	 *
	 * @param primaryKey the primary key of this venue detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the venue detail ID of this venue detail.
	 *
	 * @return the venue detail ID of this venue detail
	 */
	public long getVenueDetailId();

	/**
	 * Sets the venue detail ID of this venue detail.
	 *
	 * @param venueDetailId the venue detail ID of this venue detail
	 */
	public void setVenueDetailId(long venueDetailId);

	/**
	 * Returns the company ID of this venue detail.
	 *
	 * @return the company ID of this venue detail
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this venue detail.
	 *
	 * @param companyId the company ID of this venue detail
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this venue detail.
	 *
	 * @return the user ID of this venue detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this venue detail.
	 *
	 * @param userId the user ID of this venue detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this venue detail.
	 *
	 * @return the user uuid of this venue detail
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this venue detail.
	 *
	 * @param userUuid the user uuid of this venue detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this venue detail.
	 *
	 * @return the created date of this venue detail
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this venue detail.
	 *
	 * @param createdDate the created date of this venue detail
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this venue detail.
	 *
	 * @return the modified date of this venue detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this venue detail.
	 *
	 * @param modifiedDate the modified date of this venue detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the venue ID of this venue detail.
	 *
	 * @return the venue ID of this venue detail
	 */
	public long getVenueId();

	/**
	 * Sets the venue ID of this venue detail.
	 *
	 * @param venueId the venue ID of this venue detail
	 */
	public void setVenueId(long venueId);

	/**
	 * Returns the info type ID of this venue detail.
	 *
	 * @return the info type ID of this venue detail
	 */
	public long getInfoTypeId();

	/**
	 * Sets the info type ID of this venue detail.
	 *
	 * @param infoTypeId the info type ID of this venue detail
	 */
	public void setInfoTypeId(long infoTypeId);

	/**
	 * Returns the info type category ID of this venue detail.
	 *
	 * @return the info type category ID of this venue detail
	 */
	public long getInfoTypeCategoryId();

	/**
	 * Sets the info type category ID of this venue detail.
	 *
	 * @param infoTypeCategoryId the info type category ID of this venue detail
	 */
	public void setInfoTypeCategoryId(long infoTypeCategoryId);

	/**
	 * Returns the venue detail info name of this venue detail.
	 *
	 * @return the venue detail info name of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailInfoName();

	/**
	 * Sets the venue detail info name of this venue detail.
	 *
	 * @param venueDetailInfoName the venue detail info name of this venue detail
	 */
	public void setVenueDetailInfoName(String venueDetailInfoName);

	/**
	 * Returns the venue detail info desc of this venue detail.
	 *
	 * @return the venue detail info desc of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailInfoDesc();

	/**
	 * Sets the venue detail info desc of this venue detail.
	 *
	 * @param venueDetailInfoDesc the venue detail info desc of this venue detail
	 */
	public void setVenueDetailInfoDesc(String venueDetailInfoDesc);

	/**
	 * Returns the venue detail info comment of this venue detail.
	 *
	 * @return the venue detail info comment of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailInfoComment();

	/**
	 * Sets the venue detail info comment of this venue detail.
	 *
	 * @param venueDetailInfoComment the venue detail info comment of this venue detail
	 */
	public void setVenueDetailInfoComment(String venueDetailInfoComment);

	/**
	 * Returns the venue detail address line1 of this venue detail.
	 *
	 * @return the venue detail address line1 of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailAddressLine1();

	/**
	 * Sets the venue detail address line1 of this venue detail.
	 *
	 * @param venueDetailAddressLine1 the venue detail address line1 of this venue detail
	 */
	public void setVenueDetailAddressLine1(String venueDetailAddressLine1);

	/**
	 * Returns the venue detail address line2 of this venue detail.
	 *
	 * @return the venue detail address line2 of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailAddressLine2();

	/**
	 * Sets the venue detail address line2 of this venue detail.
	 *
	 * @param venueDetailAddressLine2 the venue detail address line2 of this venue detail
	 */
	public void setVenueDetailAddressLine2(String venueDetailAddressLine2);

	/**
	 * Returns the venue detail city of this venue detail.
	 *
	 * @return the venue detail city of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailCity();

	/**
	 * Sets the venue detail city of this venue detail.
	 *
	 * @param venueDetailCity the venue detail city of this venue detail
	 */
	public void setVenueDetailCity(String venueDetailCity);

	/**
	 * Returns the venue detail state of this venue detail.
	 *
	 * @return the venue detail state of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailState();

	/**
	 * Sets the venue detail state of this venue detail.
	 *
	 * @param venueDetailState the venue detail state of this venue detail
	 */
	public void setVenueDetailState(String venueDetailState);

	/**
	 * Returns the venue detail country of this venue detail.
	 *
	 * @return the venue detail country of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailCountry();

	/**
	 * Sets the venue detail country of this venue detail.
	 *
	 * @param venueDetailCountry the venue detail country of this venue detail
	 */
	public void setVenueDetailCountry(String venueDetailCountry);

	/**
	 * Returns the venue detail latitude of this venue detail.
	 *
	 * @return the venue detail latitude of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailLatitude();

	/**
	 * Sets the venue detail latitude of this venue detail.
	 *
	 * @param venueDetailLatitude the venue detail latitude of this venue detail
	 */
	public void setVenueDetailLatitude(String venueDetailLatitude);

	/**
	 * Returns the venue detail longitude of this venue detail.
	 *
	 * @return the venue detail longitude of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailLongitude();

	/**
	 * Sets the venue detail longitude of this venue detail.
	 *
	 * @param venueDetailLongitude the venue detail longitude of this venue detail
	 */
	public void setVenueDetailLongitude(String venueDetailLongitude);

	/**
	 * Returns the venue detail phone of this venue detail.
	 *
	 * @return the venue detail phone of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailPhone();

	/**
	 * Sets the venue detail phone of this venue detail.
	 *
	 * @param venueDetailPhone the venue detail phone of this venue detail
	 */
	public void setVenueDetailPhone(String venueDetailPhone);

	/**
	 * Returns the venue detail website of this venue detail.
	 *
	 * @return the venue detail website of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailWebsite();

	/**
	 * Sets the venue detail website of this venue detail.
	 *
	 * @param venueDetailWebsite the venue detail website of this venue detail
	 */
	public void setVenueDetailWebsite(String venueDetailWebsite);

	/**
	 * Returns the venue detail cost of this venue detail.
	 *
	 * @return the venue detail cost of this venue detail
	 */
	public double getVenueDetailCost();

	/**
	 * Sets the venue detail cost of this venue detail.
	 *
	 * @param venueDetailCost the venue detail cost of this venue detail
	 */
	public void setVenueDetailCost(double venueDetailCost);

	/**
	 * Returns the venue detailhours of operation of this venue detail.
	 *
	 * @return the venue detailhours of operation of this venue detail
	 */
	@AutoEscape
	public String getVenueDetailhoursOfOperation();

	/**
	 * Sets the venue detailhours of operation of this venue detail.
	 *
	 * @param venueDetailhoursOfOperation the venue detailhours of operation of this venue detail
	 */
	public void setVenueDetailhoursOfOperation(
		String venueDetailhoursOfOperation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.VenueDetail venueDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.VenueDetail> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.VenueDetail toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.VenueDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}