/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Venue service. Represents a row in the &quot;flaskevents_Venue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.VenueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.VenueImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see Venue
 * @see com.rumbasolutions.flask.model.impl.VenueImpl
 * @see com.rumbasolutions.flask.model.impl.VenueModelImpl
 * @generated
 */
public interface VenueModel extends BaseModel<Venue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a venue model instance should use the {@link Venue} interface instead.
	 */

	/**
	 * Returns the primary key of this venue.
	 *
	 * @return the primary key of this venue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this venue.
	 *
	 * @param primaryKey the primary key of this venue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the venue ID of this venue.
	 *
	 * @return the venue ID of this venue
	 */
	public long getVenueId();

	/**
	 * Sets the venue ID of this venue.
	 *
	 * @param venueId the venue ID of this venue
	 */
	public void setVenueId(long venueId);

	/**
	 * Returns the company ID of this venue.
	 *
	 * @return the company ID of this venue
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this venue.
	 *
	 * @param companyId the company ID of this venue
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this venue.
	 *
	 * @return the user ID of this venue
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this venue.
	 *
	 * @param userId the user ID of this venue
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this venue.
	 *
	 * @return the user uuid of this venue
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this venue.
	 *
	 * @param userUuid the user uuid of this venue
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this venue.
	 *
	 * @return the created date of this venue
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this venue.
	 *
	 * @param createdDate the created date of this venue
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this venue.
	 *
	 * @return the modified date of this venue
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this venue.
	 *
	 * @param modifiedDate the modified date of this venue
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the venue name of this venue.
	 *
	 * @return the venue name of this venue
	 */
	@AutoEscape
	public String getVenueName();

	/**
	 * Sets the venue name of this venue.
	 *
	 * @param venueName the venue name of this venue
	 */
	public void setVenueName(String venueName);

	/**
	 * Returns the venue description of this venue.
	 *
	 * @return the venue description of this venue
	 */
	@AutoEscape
	public String getVenueDescription();

	/**
	 * Sets the venue description of this venue.
	 *
	 * @param venueDescription the venue description of this venue
	 */
	public void setVenueDescription(String venueDescription);

	/**
	 * Returns the venue zip code of this venue.
	 *
	 * @return the venue zip code of this venue
	 */
	@AutoEscape
	public String getVenueZipCode();

	/**
	 * Sets the venue zip code of this venue.
	 *
	 * @param venueZipCode the venue zip code of this venue
	 */
	public void setVenueZipCode(String venueZipCode);

	/**
	 * Returns the addr line1 of this venue.
	 *
	 * @return the addr line1 of this venue
	 */
	@AutoEscape
	public String getAddrLine1();

	/**
	 * Sets the addr line1 of this venue.
	 *
	 * @param addrLine1 the addr line1 of this venue
	 */
	public void setAddrLine1(String addrLine1);

	/**
	 * Returns the addr line2 of this venue.
	 *
	 * @return the addr line2 of this venue
	 */
	@AutoEscape
	public String getAddrLine2();

	/**
	 * Sets the addr line2 of this venue.
	 *
	 * @param addrLine2 the addr line2 of this venue
	 */
	public void setAddrLine2(String addrLine2);

	/**
	 * Returns the venue city of this venue.
	 *
	 * @return the venue city of this venue
	 */
	@AutoEscape
	public String getVenueCity();

	/**
	 * Sets the venue city of this venue.
	 *
	 * @param venueCity the venue city of this venue
	 */
	public void setVenueCity(String venueCity);

	/**
	 * Returns the venue state ID of this venue.
	 *
	 * @return the venue state ID of this venue
	 */
	public long getVenueStateId();

	/**
	 * Sets the venue state ID of this venue.
	 *
	 * @param venueStateId the venue state ID of this venue
	 */
	public void setVenueStateId(long venueStateId);

	/**
	 * Returns the venue state name of this venue.
	 *
	 * @return the venue state name of this venue
	 */
	@AutoEscape
	public String getVenueStateName();

	/**
	 * Sets the venue state name of this venue.
	 *
	 * @param venueStateName the venue state name of this venue
	 */
	public void setVenueStateName(String venueStateName);

	/**
	 * Returns the venue country ID of this venue.
	 *
	 * @return the venue country ID of this venue
	 */
	public long getVenueCountryId();

	/**
	 * Sets the venue country ID of this venue.
	 *
	 * @param venueCountryId the venue country ID of this venue
	 */
	public void setVenueCountryId(long venueCountryId);

	/**
	 * Returns the venue country name of this venue.
	 *
	 * @return the venue country name of this venue
	 */
	@AutoEscape
	public String getVenueCountryName();

	/**
	 * Sets the venue country name of this venue.
	 *
	 * @param venueCountryName the venue country name of this venue
	 */
	public void setVenueCountryName(String venueCountryName);

	/**
	 * Returns the venue metro area of this venue.
	 *
	 * @return the venue metro area of this venue
	 */
	@AutoEscape
	public String getVenueMetroArea();

	/**
	 * Sets the venue metro area of this venue.
	 *
	 * @param venueMetroArea the venue metro area of this venue
	 */
	public void setVenueMetroArea(String venueMetroArea);

	/**
	 * Returns the longitude of this venue.
	 *
	 * @return the longitude of this venue
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this venue.
	 *
	 * @param longitude the longitude of this venue
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the latitude of this venue.
	 *
	 * @return the latitude of this venue
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this venue.
	 *
	 * @param latitude the latitude of this venue
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the venue details dist range of this venue.
	 *
	 * @return the venue details dist range of this venue
	 */
	public int getVenueDetailsDistRange();

	/**
	 * Sets the venue details dist range of this venue.
	 *
	 * @param venueDetailsDistRange the venue details dist range of this venue
	 */
	public void setVenueDetailsDistRange(int venueDetailsDistRange);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.Venue venue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.Venue> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.Venue toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.Venue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}