/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VenueDetail service. Represents a row in the &quot;flaskevents_VenueDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.VenueDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.VenueDetailImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see VenueDetail
 * @see com.rumbasolutions.flask.model.impl.VenueDetailImpl
 * @see com.rumbasolutions.flask.model.impl.VenueDetailModelImpl
 * @generated
 */
public interface VenueDetailModel extends BaseModel<VenueDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a venue detail model instance should use the {@link VenueDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this venue detail.
	 *
	 * @return the primary key of this venue detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this venue detail.
	 *
	 * @param primaryKey the primary key of this venue detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the venue detail ID of this venue detail.
	 *
	 * @return the venue detail ID of this venue detail
	 */
	public long getVenueDetailId();

	/**
	 * Sets the venue detail ID of this venue detail.
	 *
	 * @param venueDetailId the venue detail ID of this venue detail
	 */
	public void setVenueDetailId(long venueDetailId);

	/**
	 * Returns the company ID of this venue detail.
	 *
	 * @return the company ID of this venue detail
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this venue detail.
	 *
	 * @param companyId the company ID of this venue detail
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this venue detail.
	 *
	 * @return the user ID of this venue detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this venue detail.
	 *
	 * @param userId the user ID of this venue detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this venue detail.
	 *
	 * @return the user uuid of this venue detail
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this venue detail.
	 *
	 * @param userUuid the user uuid of this venue detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this venue detail.
	 *
	 * @return the created date of this venue detail
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this venue detail.
	 *
	 * @param createdDate the created date of this venue detail
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this venue detail.
	 *
	 * @return the modified date of this venue detail
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this venue detail.
	 *
	 * @param modifiedDate the modified date of this venue detail
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the venue ID of this venue detail.
	 *
	 * @return the venue ID of this venue detail
	 */
	public long getVenueId();

	/**
	 * Sets the venue ID of this venue detail.
	 *
	 * @param venueId the venue ID of this venue detail
	 */
	public void setVenueId(long venueId);

	/**
	 * Returns the info type ID of this venue detail.
	 *
	 * @return the info type ID of this venue detail
	 */
	public long getInfoTypeId();

	/**
	 * Sets the info type ID of this venue detail.
	 *
	 * @param infoTypeId the info type ID of this venue detail
	 */
	public void setInfoTypeId(long infoTypeId);

	/**
	 * Returns the info type name of this venue detail.
	 *
	 * @return the info type name of this venue detail
	 */
	@AutoEscape
	public String getInfoTypeName();

	/**
	 * Sets the info type name of this venue detail.
	 *
	 * @param infoTypeName the info type name of this venue detail
	 */
	public void setInfoTypeName(String infoTypeName);

	/**
	 * Returns the info type category ID of this venue detail.
	 *
	 * @return the info type category ID of this venue detail
	 */
	public long getInfoTypeCategoryId();

	/**
	 * Sets the info type category ID of this venue detail.
	 *
	 * @param infoTypeCategoryId the info type category ID of this venue detail
	 */
	public void setInfoTypeCategoryId(long infoTypeCategoryId);

	/**
	 * Returns the info type category name of this venue detail.
	 *
	 * @return the info type category name of this venue detail
	 */
	@AutoEscape
	public String getInfoTypeCategoryName();

	/**
	 * Sets the info type category name of this venue detail.
	 *
	 * @param infoTypeCategoryName the info type category name of this venue detail
	 */
	public void setInfoTypeCategoryName(String infoTypeCategoryName);

	/**
	 * Returns the info title of this venue detail.
	 *
	 * @return the info title of this venue detail
	 */
	@AutoEscape
	public String getInfoTitle();

	/**
	 * Sets the info title of this venue detail.
	 *
	 * @param infoTitle the info title of this venue detail
	 */
	public void setInfoTitle(String infoTitle);

	/**
	 * Returns the info desc of this venue detail.
	 *
	 * @return the info desc of this venue detail
	 */
	@AutoEscape
	public String getInfoDesc();

	/**
	 * Sets the info desc of this venue detail.
	 *
	 * @param infoDesc the info desc of this venue detail
	 */
	public void setInfoDesc(String infoDesc);

	/**
	 * Returns the addr line1 of this venue detail.
	 *
	 * @return the addr line1 of this venue detail
	 */
	@AutoEscape
	public String getAddrLine1();

	/**
	 * Sets the addr line1 of this venue detail.
	 *
	 * @param addrLine1 the addr line1 of this venue detail
	 */
	public void setAddrLine1(String addrLine1);

	/**
	 * Returns the addr line2 of this venue detail.
	 *
	 * @return the addr line2 of this venue detail
	 */
	@AutoEscape
	public String getAddrLine2();

	/**
	 * Sets the addr line2 of this venue detail.
	 *
	 * @param addrLine2 the addr line2 of this venue detail
	 */
	public void setAddrLine2(String addrLine2);

	/**
	 * Returns the city of this venue detail.
	 *
	 * @return the city of this venue detail
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this venue detail.
	 *
	 * @param city the city of this venue detail
	 */
	public void setCity(String city);

	/**
	 * Returns the zip code of this venue detail.
	 *
	 * @return the zip code of this venue detail
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this venue detail.
	 *
	 * @param zipCode the zip code of this venue detail
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the state ID of this venue detail.
	 *
	 * @return the state ID of this venue detail
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this venue detail.
	 *
	 * @param stateId the state ID of this venue detail
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the state name of this venue detail.
	 *
	 * @return the state name of this venue detail
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this venue detail.
	 *
	 * @param stateName the state name of this venue detail
	 */
	public void setStateName(String stateName);

	/**
	 * Returns the country ID of this venue detail.
	 *
	 * @return the country ID of this venue detail
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this venue detail.
	 *
	 * @param countryId the country ID of this venue detail
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the country name of this venue detail.
	 *
	 * @return the country name of this venue detail
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this venue detail.
	 *
	 * @param countryName the country name of this venue detail
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the latitude of this venue detail.
	 *
	 * @return the latitude of this venue detail
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this venue detail.
	 *
	 * @param latitude the latitude of this venue detail
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this venue detail.
	 *
	 * @return the longitude of this venue detail
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this venue detail.
	 *
	 * @param longitude the longitude of this venue detail
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the phone of this venue detail.
	 *
	 * @return the phone of this venue detail
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this venue detail.
	 *
	 * @param phone the phone of this venue detail
	 */
	public void setPhone(String phone);

	/**
	 * Returns the website of this venue detail.
	 *
	 * @return the website of this venue detail
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this venue detail.
	 *
	 * @param website the website of this venue detail
	 */
	public void setWebsite(String website);

	/**
	 * Returns the cost of this venue detail.
	 *
	 * @return the cost of this venue detail
	 */
	public double getCost();

	/**
	 * Sets the cost of this venue detail.
	 *
	 * @param cost the cost of this venue detail
	 */
	public void setCost(double cost);

	/**
	 * Returns the hours of operation of this venue detail.
	 *
	 * @return the hours of operation of this venue detail
	 */
	@AutoEscape
	public String getHoursOfOperation();

	/**
	 * Sets the hours of operation of this venue detail.
	 *
	 * @param hoursOfOperation the hours of operation of this venue detail
	 */
	public void setHoursOfOperation(String hoursOfOperation);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.VenueDetail venueDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.VenueDetail> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.VenueDetail toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.VenueDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}