/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SupplyList service. Represents a row in the &quot;flasktailgate_SupplyList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.SupplyListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.SupplyListImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplyList
 * @see com.rumbasolutions.flask.model.impl.SupplyListImpl
 * @see com.rumbasolutions.flask.model.impl.SupplyListModelImpl
 * @generated
 */
public interface SupplyListModel extends BaseModel<SupplyList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supply list model instance should use the {@link SupplyList} interface instead.
	 */

	/**
	 * Returns the primary key of this supply list.
	 *
	 * @return the primary key of this supply list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supply list.
	 *
	 * @param primaryKey the primary key of this supply list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supply list ID of this supply list.
	 *
	 * @return the supply list ID of this supply list
	 */
	public long getSupplyListId();

	/**
	 * Sets the supply list ID of this supply list.
	 *
	 * @param supplyListId the supply list ID of this supply list
	 */
	public void setSupplyListId(long supplyListId);

	/**
	 * Returns the supply list name of this supply list.
	 *
	 * @return the supply list name of this supply list
	 */
	@AutoEscape
	public String getSupplyListName();

	/**
	 * Sets the supply list name of this supply list.
	 *
	 * @param supplyListName the supply list name of this supply list
	 */
	public void setSupplyListName(String supplyListName);

	/**
	 * Returns the is system of this supply list.
	 *
	 * @return the is system of this supply list
	 */
	public boolean getIsSystem();

	/**
	 * Returns <code>true</code> if this supply list is is system.
	 *
	 * @return <code>true</code> if this supply list is is system; <code>false</code> otherwise
	 */
	public boolean isIsSystem();

	/**
	 * Sets whether this supply list is is system.
	 *
	 * @param isSystem the is system of this supply list
	 */
	public void setIsSystem(boolean isSystem);

	/**
	 * Returns the company ID of this supply list.
	 *
	 * @return the company ID of this supply list
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this supply list.
	 *
	 * @param companyId the company ID of this supply list
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this supply list.
	 *
	 * @return the user ID of this supply list
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this supply list.
	 *
	 * @param userId the user ID of this supply list
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this supply list.
	 *
	 * @return the user uuid of this supply list
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this supply list.
	 *
	 * @param userUuid the user uuid of this supply list
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this supply list.
	 *
	 * @return the created date of this supply list
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this supply list.
	 *
	 * @param createdDate the created date of this supply list
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this supply list.
	 *
	 * @return the modified date of this supply list
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this supply list.
	 *
	 * @param modifiedDate the modified date of this supply list
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.SupplyList supplyList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.SupplyList> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.SupplyList toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.SupplyList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}