/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SupplyItem service. Represents a row in the &quot;flasktailgate_SupplyItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.SupplyItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.SupplyItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplyItem
 * @see com.rumbasolutions.flask.model.impl.SupplyItemImpl
 * @see com.rumbasolutions.flask.model.impl.SupplyItemModelImpl
 * @generated
 */
public interface SupplyItemModel extends BaseModel<SupplyItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supply item model instance should use the {@link SupplyItem} interface instead.
	 */

	/**
	 * Returns the primary key of this supply item.
	 *
	 * @return the primary key of this supply item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supply item.
	 *
	 * @param primaryKey the primary key of this supply item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supply item ID of this supply item.
	 *
	 * @return the supply item ID of this supply item
	 */
	public long getSupplyItemId();

	/**
	 * Sets the supply item ID of this supply item.
	 *
	 * @param supplyItemId the supply item ID of this supply item
	 */
	public void setSupplyItemId(long supplyItemId);

	/**
	 * Returns the supply item name of this supply item.
	 *
	 * @return the supply item name of this supply item
	 */
	@AutoEscape
	public String getSupplyItemName();

	/**
	 * Sets the supply item name of this supply item.
	 *
	 * @param supplyItemName the supply item name of this supply item
	 */
	public void setSupplyItemName(String supplyItemName);

	/**
	 * Returns the supply list ID of this supply item.
	 *
	 * @return the supply list ID of this supply item
	 */
	public long getSupplyListId();

	/**
	 * Sets the supply list ID of this supply item.
	 *
	 * @param supplyListId the supply list ID of this supply item
	 */
	public void setSupplyListId(long supplyListId);

	/**
	 * Returns the created date of this supply item.
	 *
	 * @return the created date of this supply item
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this supply item.
	 *
	 * @param createdDate the created date of this supply item
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this supply item.
	 *
	 * @return the modified date of this supply item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this supply item.
	 *
	 * @param modifiedDate the modified date of this supply item
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.SupplyItem supplyItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.SupplyItem> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.SupplyItem toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.SupplyItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}