/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TailgateImages service. Represents a row in the &quot;flasktailgate_TailgateImages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.TailgateImagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.TailgateImagesImpl}.
 * </p>
 *
 * @author rajeshj
 * @see TailgateImages
 * @see com.rumbasolutions.flask.model.impl.TailgateImagesImpl
 * @see com.rumbasolutions.flask.model.impl.TailgateImagesModelImpl
 * @generated
 */
public interface TailgateImagesModel extends BaseModel<TailgateImages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tailgate images model instance should use the {@link TailgateImages} interface instead.
	 */

	/**
	 * Returns the primary key of this tailgate images.
	 *
	 * @return the primary key of this tailgate images
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tailgate images.
	 *
	 * @param primaryKey the primary key of this tailgate images
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tailgate image ID of this tailgate images.
	 *
	 * @return the tailgate image ID of this tailgate images
	 */
	public long getTailgateImageId();

	/**
	 * Sets the tailgate image ID of this tailgate images.
	 *
	 * @param tailgateImageId the tailgate image ID of this tailgate images
	 */
	public void setTailgateImageId(long tailgateImageId);

	/**
	 * Returns the tailgate ID of this tailgate images.
	 *
	 * @return the tailgate ID of this tailgate images
	 */
	public long getTailgateId();

	/**
	 * Sets the tailgate ID of this tailgate images.
	 *
	 * @param tailgateId the tailgate ID of this tailgate images
	 */
	public void setTailgateId(long tailgateId);

	/**
	 * Returns the user ID of this tailgate images.
	 *
	 * @return the user ID of this tailgate images
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tailgate images.
	 *
	 * @param userId the user ID of this tailgate images
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tailgate images.
	 *
	 * @return the user uuid of this tailgate images
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tailgate images.
	 *
	 * @param userUuid the user uuid of this tailgate images
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the image title of this tailgate images.
	 *
	 * @return the image title of this tailgate images
	 */
	@AutoEscape
	public String getImageTitle();

	/**
	 * Sets the image title of this tailgate images.
	 *
	 * @param imageTitle the image title of this tailgate images
	 */
	public void setImageTitle(String imageTitle);

	/**
	 * Returns the image desc of this tailgate images.
	 *
	 * @return the image desc of this tailgate images
	 */
	@AutoEscape
	public String getImageDesc();

	/**
	 * Sets the image desc of this tailgate images.
	 *
	 * @param imageDesc the image desc of this tailgate images
	 */
	public void setImageDesc(String imageDesc);

	/**
	 * Returns the image u u i d of this tailgate images.
	 *
	 * @return the image u u i d of this tailgate images
	 */
	@AutoEscape
	public String getImageUUID();

	/**
	 * Sets the image u u i d of this tailgate images.
	 *
	 * @param imageUUID the image u u i d of this tailgate images
	 */
	public void setImageUUID(String imageUUID);

	/**
	 * Returns the image group ID of this tailgate images.
	 *
	 * @return the image group ID of this tailgate images
	 */
	public long getImageGroupId();

	/**
	 * Sets the image group ID of this tailgate images.
	 *
	 * @param imageGroupId the image group ID of this tailgate images
	 */
	public void setImageGroupId(long imageGroupId);

	/**
	 * Returns the created date of this tailgate images.
	 *
	 * @return the created date of this tailgate images
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this tailgate images.
	 *
	 * @param createdDate the created date of this tailgate images
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this tailgate images.
	 *
	 * @return the modified date of this tailgate images
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tailgate images.
	 *
	 * @param modifiedDate the modified date of this tailgate images
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.TailgateImages tailgateImages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.TailgateImages> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateImages toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateImages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}