/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TailgateMessageBoard service. Represents a row in the &quot;flasktailgate_TailgateMessageBoard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.TailgateMessageBoardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.TailgateMessageBoardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TailgateMessageBoard
 * @see com.rumbasolutions.flask.model.impl.TailgateMessageBoardImpl
 * @see com.rumbasolutions.flask.model.impl.TailgateMessageBoardModelImpl
 * @generated
 */
public interface TailgateMessageBoardModel extends BaseModel<TailgateMessageBoard> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tailgate message board model instance should use the {@link TailgateMessageBoard} interface instead.
	 */

	/**
	 * Returns the primary key of this tailgate message board.
	 *
	 * @return the primary key of this tailgate message board
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tailgate message board.
	 *
	 * @param primaryKey the primary key of this tailgate message board
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tailgate message ID of this tailgate message board.
	 *
	 * @return the tailgate message ID of this tailgate message board
	 */
	public long getTailgateMessageId();

	/**
	 * Sets the tailgate message ID of this tailgate message board.
	 *
	 * @param tailgateMessageId the tailgate message ID of this tailgate message board
	 */
	public void setTailgateMessageId(long tailgateMessageId);

	/**
	 * Returns the message text of this tailgate message board.
	 *
	 * @return the message text of this tailgate message board
	 */
	@AutoEscape
	public String getMessageText();

	/**
	 * Sets the message text of this tailgate message board.
	 *
	 * @param messageText the message text of this tailgate message board
	 */
	public void setMessageText(String messageText);

	/**
	 * Returns the tailgate ID of this tailgate message board.
	 *
	 * @return the tailgate ID of this tailgate message board
	 */
	public long getTailgateId();

	/**
	 * Sets the tailgate ID of this tailgate message board.
	 *
	 * @param tailgateId the tailgate ID of this tailgate message board
	 */
	public void setTailgateId(long tailgateId);

	/**
	 * Returns the company ID of this tailgate message board.
	 *
	 * @return the company ID of this tailgate message board
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this tailgate message board.
	 *
	 * @param companyId the company ID of this tailgate message board
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tailgate message board.
	 *
	 * @return the user ID of this tailgate message board
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tailgate message board.
	 *
	 * @param userId the user ID of this tailgate message board
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tailgate message board.
	 *
	 * @return the user uuid of this tailgate message board
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tailgate message board.
	 *
	 * @param userUuid the user uuid of this tailgate message board
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this tailgate message board.
	 *
	 * @return the created date of this tailgate message board
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this tailgate message board.
	 *
	 * @param createdDate the created date of this tailgate message board
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this tailgate message board.
	 *
	 * @return the modified date of this tailgate message board
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tailgate message board.
	 *
	 * @param modifiedDate the modified date of this tailgate message board
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.TailgateMessageBoard tailgateMessageBoard);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.TailgateMessageBoard> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateMessageBoard toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateMessageBoard toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}