/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TailgateInfo service. Represents a row in the &quot;flasktailgate_TailgateInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.TailgateInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.TailgateInfoImpl}.
 * </p>
 *
 * @author rajeshj
 * @see TailgateInfo
 * @see com.rumbasolutions.flask.model.impl.TailgateInfoImpl
 * @see com.rumbasolutions.flask.model.impl.TailgateInfoModelImpl
 * @generated
 */
public interface TailgateInfoModel extends BaseModel<TailgateInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tailgate info model instance should use the {@link TailgateInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this tailgate info.
	 *
	 * @return the primary key of this tailgate info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tailgate info.
	 *
	 * @param primaryKey the primary key of this tailgate info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tailgate ID of this tailgate info.
	 *
	 * @return the tailgate ID of this tailgate info
	 */
	public long getTailgateId();

	/**
	 * Sets the tailgate ID of this tailgate info.
	 *
	 * @param tailgateId the tailgate ID of this tailgate info
	 */
	public void setTailgateId(long tailgateId);

	/**
	 * Returns the company ID of this tailgate info.
	 *
	 * @return the company ID of this tailgate info
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this tailgate info.
	 *
	 * @param companyId the company ID of this tailgate info
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tailgate info.
	 *
	 * @return the user ID of this tailgate info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tailgate info.
	 *
	 * @param userId the user ID of this tailgate info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tailgate info.
	 *
	 * @return the user uuid of this tailgate info
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tailgate info.
	 *
	 * @param userUuid the user uuid of this tailgate info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this tailgate info.
	 *
	 * @return the created date of this tailgate info
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this tailgate info.
	 *
	 * @param createdDate the created date of this tailgate info
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this tailgate info.
	 *
	 * @return the modified date of this tailgate info
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tailgate info.
	 *
	 * @param modifiedDate the modified date of this tailgate info
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tailgate name of this tailgate info.
	 *
	 * @return the tailgate name of this tailgate info
	 */
	@AutoEscape
	public String getTailgateName();

	/**
	 * Sets the tailgate name of this tailgate info.
	 *
	 * @param tailgateName the tailgate name of this tailgate info
	 */
	public void setTailgateName(String tailgateName);

	/**
	 * Returns the tailgate description of this tailgate info.
	 *
	 * @return the tailgate description of this tailgate info
	 */
	@AutoEscape
	public String getTailgateDescription();

	/**
	 * Sets the tailgate description of this tailgate info.
	 *
	 * @param tailgateDescription the tailgate description of this tailgate info
	 */
	public void setTailgateDescription(String tailgateDescription);

	/**
	 * Returns the event ID of this tailgate info.
	 *
	 * @return the event ID of this tailgate info
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this tailgate info.
	 *
	 * @param eventId the event ID of this tailgate info
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the event name of this tailgate info.
	 *
	 * @return the event name of this tailgate info
	 */
	@AutoEscape
	public String getEventName();

	/**
	 * Sets the event name of this tailgate info.
	 *
	 * @param eventName the event name of this tailgate info
	 */
	public void setEventName(String eventName);

	/**
	 * Returns the tailgate date of this tailgate info.
	 *
	 * @return the tailgate date of this tailgate info
	 */
	public Date getTailgateDate();

	/**
	 * Sets the tailgate date of this tailgate info.
	 *
	 * @param tailgateDate the tailgate date of this tailgate info
	 */
	public void setTailgateDate(Date tailgateDate);

	/**
	 * Returns the start time of this tailgate info.
	 *
	 * @return the start time of this tailgate info
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this tailgate info.
	 *
	 * @param startTime the start time of this tailgate info
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this tailgate info.
	 *
	 * @return the end time of this tailgate info
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this tailgate info.
	 *
	 * @param endTime the end time of this tailgate info
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the is active of this tailgate info.
	 *
	 * @return the is active of this tailgate info
	 */
	public int getIsActive();

	/**
	 * Sets the is active of this tailgate info.
	 *
	 * @param isActive the is active of this tailgate info
	 */
	public void setIsActive(int isActive);

	/**
	 * Returns the is delete of this tailgate info.
	 *
	 * @return the is delete of this tailgate info
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this tailgate info.
	 *
	 * @param isDelete the is delete of this tailgate info
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the amount to pay of this tailgate info.
	 *
	 * @return the amount to pay of this tailgate info
	 */
	public double getAmountToPay();

	/**
	 * Sets the amount to pay of this tailgate info.
	 *
	 * @param amountToPay the amount to pay of this tailgate info
	 */
	public void setAmountToPay(double amountToPay);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.TailgateInfo tailgateInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.TailgateInfo> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateInfo toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}