/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TailgateSupplyItem service. Represents a row in the &quot;flasktailgate_TailgateSupplyItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.TailgateSupplyItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.TailgateSupplyItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TailgateSupplyItem
 * @see com.rumbasolutions.flask.model.impl.TailgateSupplyItemImpl
 * @see com.rumbasolutions.flask.model.impl.TailgateSupplyItemModelImpl
 * @generated
 */
public interface TailgateSupplyItemModel extends BaseModel<TailgateSupplyItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tailgate supply item model instance should use the {@link TailgateSupplyItem} interface instead.
	 */

	/**
	 * Returns the primary key of this tailgate supply item.
	 *
	 * @return the primary key of this tailgate supply item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tailgate supply item.
	 *
	 * @param primaryKey the primary key of this tailgate supply item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tailgate supply item ID of this tailgate supply item.
	 *
	 * @return the tailgate supply item ID of this tailgate supply item
	 */
	public long getTailgateSupplyItemId();

	/**
	 * Sets the tailgate supply item ID of this tailgate supply item.
	 *
	 * @param tailgateSupplyItemId the tailgate supply item ID of this tailgate supply item
	 */
	public void setTailgateSupplyItemId(long tailgateSupplyItemId);

	/**
	 * Returns the supply list item name of this tailgate supply item.
	 *
	 * @return the supply list item name of this tailgate supply item
	 */
	@AutoEscape
	public String getSupplyListItemName();

	/**
	 * Sets the supply list item name of this tailgate supply item.
	 *
	 * @param supplyListItemName the supply list item name of this tailgate supply item
	 */
	public void setSupplyListItemName(String supplyListItemName);

	/**
	 * Returns the tailgate ID of this tailgate supply item.
	 *
	 * @return the tailgate ID of this tailgate supply item
	 */
	public long getTailgateId();

	/**
	 * Sets the tailgate ID of this tailgate supply item.
	 *
	 * @param tailgateId the tailgate ID of this tailgate supply item
	 */
	public void setTailgateId(long tailgateId);

	/**
	 * Returns the item assigned user ID of this tailgate supply item.
	 *
	 * @return the item assigned user ID of this tailgate supply item
	 */
	public long getItemAssignedUserId();

	/**
	 * Sets the item assigned user ID of this tailgate supply item.
	 *
	 * @param itemAssignedUserId the item assigned user ID of this tailgate supply item
	 */
	public void setItemAssignedUserId(long itemAssignedUserId);

	/**
	 * Returns the item assigned user uuid of this tailgate supply item.
	 *
	 * @return the item assigned user uuid of this tailgate supply item
	 * @throws SystemException if a system exception occurred
	 */
	public String getItemAssignedUserUuid() throws SystemException;

	/**
	 * Sets the item assigned user uuid of this tailgate supply item.
	 *
	 * @param itemAssignedUserUuid the item assigned user uuid of this tailgate supply item
	 */
	public void setItemAssignedUserUuid(String itemAssignedUserUuid);

	/**
	 * Returns the company ID of this tailgate supply item.
	 *
	 * @return the company ID of this tailgate supply item
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this tailgate supply item.
	 *
	 * @param companyId the company ID of this tailgate supply item
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tailgate supply item.
	 *
	 * @return the user ID of this tailgate supply item
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tailgate supply item.
	 *
	 * @param userId the user ID of this tailgate supply item
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tailgate supply item.
	 *
	 * @return the user uuid of this tailgate supply item
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tailgate supply item.
	 *
	 * @param userUuid the user uuid of this tailgate supply item
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this tailgate supply item.
	 *
	 * @return the created date of this tailgate supply item
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this tailgate supply item.
	 *
	 * @param createdDate the created date of this tailgate supply item
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this tailgate supply item.
	 *
	 * @return the modified date of this tailgate supply item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tailgate supply item.
	 *
	 * @param modifiedDate the modified date of this tailgate supply item
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.TailgateSupplyItem tailgateSupplyItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.TailgateSupplyItem> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateSupplyItem toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.TailgateSupplyItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}