/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rumbasolutions.flask.model.FlaskGroupUsers;
import com.rumbasolutions.flask.service.FlaskGroupUsersService;
import com.rumbasolutions.flask.service.persistence.FlaskGroupFinder;
import com.rumbasolutions.flask.service.persistence.FlaskGroupPersistence;
import com.rumbasolutions.flask.service.persistence.FlaskGroupUsersFinder;
import com.rumbasolutions.flask.service.persistence.FlaskGroupUsersPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the flask group users remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rumbasolutions.flask.service.impl.FlaskGroupUsersServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.rumbasolutions.flask.service.impl.FlaskGroupUsersServiceImpl
 * @see com.rumbasolutions.flask.service.FlaskGroupUsersServiceUtil
 * @generated
 */
public abstract class FlaskGroupUsersServiceBaseImpl extends BaseServiceImpl
	implements FlaskGroupUsersService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rumbasolutions.flask.service.FlaskGroupUsersServiceUtil} to access the flask group users remote service.
	 */

	/**
	 * Returns the flask group local service.
	 *
	 * @return the flask group local service
	 */
	public com.rumbasolutions.flask.service.FlaskGroupLocalService getFlaskGroupLocalService() {
		return flaskGroupLocalService;
	}

	/**
	 * Sets the flask group local service.
	 *
	 * @param flaskGroupLocalService the flask group local service
	 */
	public void setFlaskGroupLocalService(
		com.rumbasolutions.flask.service.FlaskGroupLocalService flaskGroupLocalService) {
		this.flaskGroupLocalService = flaskGroupLocalService;
	}

	/**
	 * Returns the flask group remote service.
	 *
	 * @return the flask group remote service
	 */
	public com.rumbasolutions.flask.service.FlaskGroupService getFlaskGroupService() {
		return flaskGroupService;
	}

	/**
	 * Sets the flask group remote service.
	 *
	 * @param flaskGroupService the flask group remote service
	 */
	public void setFlaskGroupService(
		com.rumbasolutions.flask.service.FlaskGroupService flaskGroupService) {
		this.flaskGroupService = flaskGroupService;
	}

	/**
	 * Returns the flask group persistence.
	 *
	 * @return the flask group persistence
	 */
	public FlaskGroupPersistence getFlaskGroupPersistence() {
		return flaskGroupPersistence;
	}

	/**
	 * Sets the flask group persistence.
	 *
	 * @param flaskGroupPersistence the flask group persistence
	 */
	public void setFlaskGroupPersistence(
		FlaskGroupPersistence flaskGroupPersistence) {
		this.flaskGroupPersistence = flaskGroupPersistence;
	}

	/**
	 * Returns the flask group finder.
	 *
	 * @return the flask group finder
	 */
	public FlaskGroupFinder getFlaskGroupFinder() {
		return flaskGroupFinder;
	}

	/**
	 * Sets the flask group finder.
	 *
	 * @param flaskGroupFinder the flask group finder
	 */
	public void setFlaskGroupFinder(FlaskGroupFinder flaskGroupFinder) {
		this.flaskGroupFinder = flaskGroupFinder;
	}

	/**
	 * Returns the flask group users local service.
	 *
	 * @return the flask group users local service
	 */
	public com.rumbasolutions.flask.service.FlaskGroupUsersLocalService getFlaskGroupUsersLocalService() {
		return flaskGroupUsersLocalService;
	}

	/**
	 * Sets the flask group users local service.
	 *
	 * @param flaskGroupUsersLocalService the flask group users local service
	 */
	public void setFlaskGroupUsersLocalService(
		com.rumbasolutions.flask.service.FlaskGroupUsersLocalService flaskGroupUsersLocalService) {
		this.flaskGroupUsersLocalService = flaskGroupUsersLocalService;
	}

	/**
	 * Returns the flask group users remote service.
	 *
	 * @return the flask group users remote service
	 */
	public com.rumbasolutions.flask.service.FlaskGroupUsersService getFlaskGroupUsersService() {
		return flaskGroupUsersService;
	}

	/**
	 * Sets the flask group users remote service.
	 *
	 * @param flaskGroupUsersService the flask group users remote service
	 */
	public void setFlaskGroupUsersService(
		com.rumbasolutions.flask.service.FlaskGroupUsersService flaskGroupUsersService) {
		this.flaskGroupUsersService = flaskGroupUsersService;
	}

	/**
	 * Returns the flask group users persistence.
	 *
	 * @return the flask group users persistence
	 */
	public FlaskGroupUsersPersistence getFlaskGroupUsersPersistence() {
		return flaskGroupUsersPersistence;
	}

	/**
	 * Sets the flask group users persistence.
	 *
	 * @param flaskGroupUsersPersistence the flask group users persistence
	 */
	public void setFlaskGroupUsersPersistence(
		FlaskGroupUsersPersistence flaskGroupUsersPersistence) {
		this.flaskGroupUsersPersistence = flaskGroupUsersPersistence;
	}

	/**
	 * Returns the flask group users finder.
	 *
	 * @return the flask group users finder
	 */
	public FlaskGroupUsersFinder getFlaskGroupUsersFinder() {
		return flaskGroupUsersFinder;
	}

	/**
	 * Sets the flask group users finder.
	 *
	 * @param flaskGroupUsersFinder the flask group users finder
	 */
	public void setFlaskGroupUsersFinder(
		FlaskGroupUsersFinder flaskGroupUsersFinder) {
		this.flaskGroupUsersFinder = flaskGroupUsersFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return FlaskGroupUsers.class;
	}

	protected String getModelClassName() {
		return FlaskGroupUsers.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = flaskGroupUsersPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rumbasolutions.flask.service.FlaskGroupLocalService.class)
	protected com.rumbasolutions.flask.service.FlaskGroupLocalService flaskGroupLocalService;
	@BeanReference(type = com.rumbasolutions.flask.service.FlaskGroupService.class)
	protected com.rumbasolutions.flask.service.FlaskGroupService flaskGroupService;
	@BeanReference(type = FlaskGroupPersistence.class)
	protected FlaskGroupPersistence flaskGroupPersistence;
	@BeanReference(type = FlaskGroupFinder.class)
	protected FlaskGroupFinder flaskGroupFinder;
	@BeanReference(type = com.rumbasolutions.flask.service.FlaskGroupUsersLocalService.class)
	protected com.rumbasolutions.flask.service.FlaskGroupUsersLocalService flaskGroupUsersLocalService;
	@BeanReference(type = com.rumbasolutions.flask.service.FlaskGroupUsersService.class)
	protected com.rumbasolutions.flask.service.FlaskGroupUsersService flaskGroupUsersService;
	@BeanReference(type = FlaskGroupUsersPersistence.class)
	protected FlaskGroupUsersPersistence flaskGroupUsersPersistence;
	@BeanReference(type = FlaskGroupUsersFinder.class)
	protected FlaskGroupUsersFinder flaskGroupUsersFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private FlaskGroupUsersServiceClpInvoker _clpInvoker = new FlaskGroupUsersServiceClpInvoker();
}