/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rumbasolutions.flask.model.TailgateImages;
import com.rumbasolutions.flask.model.TailgateImagesModel;
import com.rumbasolutions.flask.model.TailgateImagesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TailgateImages service. Represents a row in the &quot;flasktailgate_TailgateImages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rumbasolutions.flask.model.TailgateImagesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TailgateImagesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TailgateImagesImpl
 * @see com.rumbasolutions.flask.model.TailgateImages
 * @see com.rumbasolutions.flask.model.TailgateImagesModel
 * @generated
 */
@JSON(strict = true)
public class TailgateImagesModelImpl extends BaseModelImpl<TailgateImages>
	implements TailgateImagesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tailgate images model instance should use the {@link com.rumbasolutions.flask.model.TailgateImages} interface instead.
	 */
	public static final String TABLE_NAME = "flasktailgate_TailgateImages";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tailgateImageId", Types.BIGINT },
			{ "tailgateId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "imageTitle", Types.VARCHAR },
			{ "imageDesc", Types.VARCHAR },
			{ "imageUUID", Types.VARCHAR },
			{ "imageGroupId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table flasktailgate_TailgateImages (tailgateImageId LONG not null primary key,tailgateId LONG,userId LONG,imageTitle VARCHAR(75) null,imageDesc VARCHAR(75) null,imageUUID VARCHAR(75) null,imageGroupId LONG,createdDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table flasktailgate_TailgateImages";
	public static final String ORDER_BY_JPQL = " ORDER BY tailgateImages.tailgateImageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY flasktailgate_TailgateImages.tailgateImageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rumbasolutions.flask.model.TailgateImages"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rumbasolutions.flask.model.TailgateImages"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rumbasolutions.flask.model.TailgateImages"),
			true);
	public static long IMAGEUUID_COLUMN_BITMASK = 1L;
	public static long TAILGATEID_COLUMN_BITMASK = 2L;
	public static long TAILGATEIMAGEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TailgateImages toModel(TailgateImagesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TailgateImages model = new TailgateImagesImpl();

		model.setTailgateImageId(soapModel.getTailgateImageId());
		model.setTailgateId(soapModel.getTailgateId());
		model.setUserId(soapModel.getUserId());
		model.setImageTitle(soapModel.getImageTitle());
		model.setImageDesc(soapModel.getImageDesc());
		model.setImageUUID(soapModel.getImageUUID());
		model.setImageGroupId(soapModel.getImageGroupId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TailgateImages> toModels(TailgateImagesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TailgateImages> models = new ArrayList<TailgateImages>(soapModels.length);

		for (TailgateImagesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rumbasolutions.flask.model.TailgateImages"));

	public TailgateImagesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tailgateImageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTailgateImageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tailgateImageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TailgateImages.class;
	}

	@Override
	public String getModelClassName() {
		return TailgateImages.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tailgateImageId", getTailgateImageId());
		attributes.put("tailgateId", getTailgateId());
		attributes.put("userId", getUserId());
		attributes.put("imageTitle", getImageTitle());
		attributes.put("imageDesc", getImageDesc());
		attributes.put("imageUUID", getImageUUID());
		attributes.put("imageGroupId", getImageGroupId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tailgateImageId = (Long)attributes.get("tailgateImageId");

		if (tailgateImageId != null) {
			setTailgateImageId(tailgateImageId);
		}

		Long tailgateId = (Long)attributes.get("tailgateId");

		if (tailgateId != null) {
			setTailgateId(tailgateId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String imageTitle = (String)attributes.get("imageTitle");

		if (imageTitle != null) {
			setImageTitle(imageTitle);
		}

		String imageDesc = (String)attributes.get("imageDesc");

		if (imageDesc != null) {
			setImageDesc(imageDesc);
		}

		String imageUUID = (String)attributes.get("imageUUID");

		if (imageUUID != null) {
			setImageUUID(imageUUID);
		}

		Long imageGroupId = (Long)attributes.get("imageGroupId");

		if (imageGroupId != null) {
			setImageGroupId(imageGroupId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getTailgateImageId() {
		return _tailgateImageId;
	}

	@Override
	public void setTailgateImageId(long tailgateImageId) {
		_tailgateImageId = tailgateImageId;
	}

	@JSON
	@Override
	public long getTailgateId() {
		return _tailgateId;
	}

	@Override
	public void setTailgateId(long tailgateId) {
		_columnBitmask |= TAILGATEID_COLUMN_BITMASK;

		if (!_setOriginalTailgateId) {
			_setOriginalTailgateId = true;

			_originalTailgateId = _tailgateId;
		}

		_tailgateId = tailgateId;
	}

	public long getOriginalTailgateId() {
		return _originalTailgateId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getImageTitle() {
		if (_imageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageTitle;
		}
	}

	@Override
	public void setImageTitle(String imageTitle) {
		_imageTitle = imageTitle;
	}

	@JSON
	@Override
	public String getImageDesc() {
		if (_imageDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageDesc;
		}
	}

	@Override
	public void setImageDesc(String imageDesc) {
		_imageDesc = imageDesc;
	}

	@JSON
	@Override
	public String getImageUUID() {
		if (_imageUUID == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUUID;
		}
	}

	@Override
	public void setImageUUID(String imageUUID) {
		_columnBitmask |= IMAGEUUID_COLUMN_BITMASK;

		if (_originalImageUUID == null) {
			_originalImageUUID = _imageUUID;
		}

		_imageUUID = imageUUID;
	}

	public String getOriginalImageUUID() {
		return GetterUtil.getString(_originalImageUUID);
	}

	@JSON
	@Override
	public long getImageGroupId() {
		return _imageGroupId;
	}

	@Override
	public void setImageGroupId(long imageGroupId) {
		_imageGroupId = imageGroupId;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TailgateImages.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TailgateImages toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TailgateImages)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TailgateImagesImpl tailgateImagesImpl = new TailgateImagesImpl();

		tailgateImagesImpl.setTailgateImageId(getTailgateImageId());
		tailgateImagesImpl.setTailgateId(getTailgateId());
		tailgateImagesImpl.setUserId(getUserId());
		tailgateImagesImpl.setImageTitle(getImageTitle());
		tailgateImagesImpl.setImageDesc(getImageDesc());
		tailgateImagesImpl.setImageUUID(getImageUUID());
		tailgateImagesImpl.setImageGroupId(getImageGroupId());
		tailgateImagesImpl.setCreatedDate(getCreatedDate());
		tailgateImagesImpl.setModifiedDate(getModifiedDate());

		tailgateImagesImpl.resetOriginalValues();

		return tailgateImagesImpl;
	}

	@Override
	public int compareTo(TailgateImages tailgateImages) {
		long primaryKey = tailgateImages.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TailgateImages)) {
			return false;
		}

		TailgateImages tailgateImages = (TailgateImages)obj;

		long primaryKey = tailgateImages.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TailgateImagesModelImpl tailgateImagesModelImpl = this;

		tailgateImagesModelImpl._originalTailgateId = tailgateImagesModelImpl._tailgateId;

		tailgateImagesModelImpl._setOriginalTailgateId = false;

		tailgateImagesModelImpl._originalImageUUID = tailgateImagesModelImpl._imageUUID;

		tailgateImagesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TailgateImages> toCacheModel() {
		TailgateImagesCacheModel tailgateImagesCacheModel = new TailgateImagesCacheModel();

		tailgateImagesCacheModel.tailgateImageId = getTailgateImageId();

		tailgateImagesCacheModel.tailgateId = getTailgateId();

		tailgateImagesCacheModel.userId = getUserId();

		tailgateImagesCacheModel.imageTitle = getImageTitle();

		String imageTitle = tailgateImagesCacheModel.imageTitle;

		if ((imageTitle != null) && (imageTitle.length() == 0)) {
			tailgateImagesCacheModel.imageTitle = null;
		}

		tailgateImagesCacheModel.imageDesc = getImageDesc();

		String imageDesc = tailgateImagesCacheModel.imageDesc;

		if ((imageDesc != null) && (imageDesc.length() == 0)) {
			tailgateImagesCacheModel.imageDesc = null;
		}

		tailgateImagesCacheModel.imageUUID = getImageUUID();

		String imageUUID = tailgateImagesCacheModel.imageUUID;

		if ((imageUUID != null) && (imageUUID.length() == 0)) {
			tailgateImagesCacheModel.imageUUID = null;
		}

		tailgateImagesCacheModel.imageGroupId = getImageGroupId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			tailgateImagesCacheModel.createdDate = createdDate.getTime();
		}
		else {
			tailgateImagesCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tailgateImagesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tailgateImagesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return tailgateImagesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{tailgateImageId=");
		sb.append(getTailgateImageId());
		sb.append(", tailgateId=");
		sb.append(getTailgateId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", imageTitle=");
		sb.append(getImageTitle());
		sb.append(", imageDesc=");
		sb.append(getImageDesc());
		sb.append(", imageUUID=");
		sb.append(getImageUUID());
		sb.append(", imageGroupId=");
		sb.append(getImageGroupId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rumbasolutions.flask.model.TailgateImages");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tailgateImageId</column-name><column-value><![CDATA[");
		sb.append(getTailgateImageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tailgateId</column-name><column-value><![CDATA[");
		sb.append(getTailgateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageTitle</column-name><column-value><![CDATA[");
		sb.append(getImageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageDesc</column-name><column-value><![CDATA[");
		sb.append(getImageDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUUID</column-name><column-value><![CDATA[");
		sb.append(getImageUUID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageGroupId</column-name><column-value><![CDATA[");
		sb.append(getImageGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TailgateImages.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TailgateImages.class
		};
	private long _tailgateImageId;
	private long _tailgateId;
	private long _originalTailgateId;
	private boolean _setOriginalTailgateId;
	private long _userId;
	private String _userUuid;
	private String _imageTitle;
	private String _imageDesc;
	private String _imageUUID;
	private String _originalImageUUID;
	private long _imageGroupId;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private TailgateImages _escapedModel;
}