/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rumbasolutions.flask.model.TailgateMessageBoard;
import com.rumbasolutions.flask.model.TailgateMessageBoardModel;
import com.rumbasolutions.flask.model.TailgateMessageBoardSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TailgateMessageBoard service. Represents a row in the &quot;flasktailgate_TailgateMessageBoard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rumbasolutions.flask.model.TailgateMessageBoardModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TailgateMessageBoardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TailgateMessageBoardImpl
 * @see com.rumbasolutions.flask.model.TailgateMessageBoard
 * @see com.rumbasolutions.flask.model.TailgateMessageBoardModel
 * @generated
 */
@JSON(strict = true)
public class TailgateMessageBoardModelImpl extends BaseModelImpl<TailgateMessageBoard>
	implements TailgateMessageBoardModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tailgate message board model instance should use the {@link com.rumbasolutions.flask.model.TailgateMessageBoard} interface instead.
	 */
	public static final String TABLE_NAME = "flasktailgate_TailgateMessageBoard";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tailgateMessageId", Types.BIGINT },
			{ "messageText", Types.VARCHAR },
			{ "tailgateId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table flasktailgate_TailgateMessageBoard (tailgateMessageId LONG not null primary key,messageText VARCHAR(75) null,tailgateId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table flasktailgate_TailgateMessageBoard";
	public static final String ORDER_BY_JPQL = " ORDER BY tailgateMessageBoard.tailgateMessageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY flasktailgate_TailgateMessageBoard.tailgateMessageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rumbasolutions.flask.model.TailgateMessageBoard"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rumbasolutions.flask.model.TailgateMessageBoard"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rumbasolutions.flask.model.TailgateMessageBoard"),
			true);
	public static long TAILGATEID_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long TAILGATEMESSAGEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TailgateMessageBoard toModel(
		TailgateMessageBoardSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TailgateMessageBoard model = new TailgateMessageBoardImpl();

		model.setTailgateMessageId(soapModel.getTailgateMessageId());
		model.setMessageText(soapModel.getMessageText());
		model.setTailgateId(soapModel.getTailgateId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TailgateMessageBoard> toModels(
		TailgateMessageBoardSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TailgateMessageBoard> models = new ArrayList<TailgateMessageBoard>(soapModels.length);

		for (TailgateMessageBoardSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rumbasolutions.flask.model.TailgateMessageBoard"));

	public TailgateMessageBoardModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tailgateMessageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTailgateMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tailgateMessageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TailgateMessageBoard.class;
	}

	@Override
	public String getModelClassName() {
		return TailgateMessageBoard.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tailgateMessageId", getTailgateMessageId());
		attributes.put("messageText", getMessageText());
		attributes.put("tailgateId", getTailgateId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long tailgateMessageId = (Long)attributes.get("tailgateMessageId");

		if (tailgateMessageId != null) {
			setTailgateMessageId(tailgateMessageId);
		}

		String messageText = (String)attributes.get("messageText");

		if (messageText != null) {
			setMessageText(messageText);
		}

		Long tailgateId = (Long)attributes.get("tailgateId");

		if (tailgateId != null) {
			setTailgateId(tailgateId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public long getTailgateMessageId() {
		return _tailgateMessageId;
	}

	@Override
	public void setTailgateMessageId(long tailgateMessageId) {
		_tailgateMessageId = tailgateMessageId;
	}

	@JSON
	@Override
	public String getMessageText() {
		if (_messageText == null) {
			return StringPool.BLANK;
		}
		else {
			return _messageText;
		}
	}

	@Override
	public void setMessageText(String messageText) {
		_messageText = messageText;
	}

	@JSON
	@Override
	public long getTailgateId() {
		return _tailgateId;
	}

	@Override
	public void setTailgateId(long tailgateId) {
		_columnBitmask |= TAILGATEID_COLUMN_BITMASK;

		if (!_setOriginalTailgateId) {
			_setOriginalTailgateId = true;

			_originalTailgateId = _tailgateId;
		}

		_tailgateId = tailgateId;
	}

	public long getOriginalTailgateId() {
		return _originalTailgateId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TailgateMessageBoard.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TailgateMessageBoard toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TailgateMessageBoard)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TailgateMessageBoardImpl tailgateMessageBoardImpl = new TailgateMessageBoardImpl();

		tailgateMessageBoardImpl.setTailgateMessageId(getTailgateMessageId());
		tailgateMessageBoardImpl.setMessageText(getMessageText());
		tailgateMessageBoardImpl.setTailgateId(getTailgateId());
		tailgateMessageBoardImpl.setCompanyId(getCompanyId());
		tailgateMessageBoardImpl.setUserId(getUserId());
		tailgateMessageBoardImpl.setCreatedDate(getCreatedDate());
		tailgateMessageBoardImpl.setModifiedDate(getModifiedDate());

		tailgateMessageBoardImpl.resetOriginalValues();

		return tailgateMessageBoardImpl;
	}

	@Override
	public int compareTo(TailgateMessageBoard tailgateMessageBoard) {
		long primaryKey = tailgateMessageBoard.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TailgateMessageBoard)) {
			return false;
		}

		TailgateMessageBoard tailgateMessageBoard = (TailgateMessageBoard)obj;

		long primaryKey = tailgateMessageBoard.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TailgateMessageBoardModelImpl tailgateMessageBoardModelImpl = this;

		tailgateMessageBoardModelImpl._originalTailgateId = tailgateMessageBoardModelImpl._tailgateId;

		tailgateMessageBoardModelImpl._setOriginalTailgateId = false;

		tailgateMessageBoardModelImpl._originalUserId = tailgateMessageBoardModelImpl._userId;

		tailgateMessageBoardModelImpl._setOriginalUserId = false;

		tailgateMessageBoardModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TailgateMessageBoard> toCacheModel() {
		TailgateMessageBoardCacheModel tailgateMessageBoardCacheModel = new TailgateMessageBoardCacheModel();

		tailgateMessageBoardCacheModel.tailgateMessageId = getTailgateMessageId();

		tailgateMessageBoardCacheModel.messageText = getMessageText();

		String messageText = tailgateMessageBoardCacheModel.messageText;

		if ((messageText != null) && (messageText.length() == 0)) {
			tailgateMessageBoardCacheModel.messageText = null;
		}

		tailgateMessageBoardCacheModel.tailgateId = getTailgateId();

		tailgateMessageBoardCacheModel.companyId = getCompanyId();

		tailgateMessageBoardCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			tailgateMessageBoardCacheModel.createdDate = createdDate.getTime();
		}
		else {
			tailgateMessageBoardCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tailgateMessageBoardCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tailgateMessageBoardCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return tailgateMessageBoardCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{tailgateMessageId=");
		sb.append(getTailgateMessageId());
		sb.append(", messageText=");
		sb.append(getMessageText());
		sb.append(", tailgateId=");
		sb.append(getTailgateId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rumbasolutions.flask.model.TailgateMessageBoard");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tailgateMessageId</column-name><column-value><![CDATA[");
		sb.append(getTailgateMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageText</column-name><column-value><![CDATA[");
		sb.append(getMessageText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tailgateId</column-name><column-value><![CDATA[");
		sb.append(getTailgateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TailgateMessageBoard.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TailgateMessageBoard.class
		};
	private long _tailgateMessageId;
	private String _messageText;
	private long _tailgateId;
	private long _originalTailgateId;
	private boolean _setOriginalTailgateId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private TailgateMessageBoard _escapedModel;
}