/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the InvitationInfo service. Represents a row in the &quot;flaskinvitation_InvitationInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.InvitationInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.InvitationInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvitationInfo
 * @see com.rumbasolutions.flask.model.impl.InvitationInfoImpl
 * @see com.rumbasolutions.flask.model.impl.InvitationInfoModelImpl
 * @generated
 */
public interface InvitationInfoModel extends BaseModel<InvitationInfo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invitation info model instance should use the {@link InvitationInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this invitation info.
	 *
	 * @return the primary key of this invitation info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invitation info.
	 *
	 * @param primaryKey the primary key of this invitation info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inviation ID of this invitation info.
	 *
	 * @return the inviation ID of this invitation info
	 */
	public long getInviationId();

	/**
	 * Sets the inviation ID of this invitation info.
	 *
	 * @param inviationId the inviation ID of this invitation info
	 */
	public void setInviationId(long inviationId);

	/**
	 * Returns the name of this invitation info.
	 *
	 * @return the name of this invitation info
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this invitation info.
	 *
	 * @param name the name of this invitation info
	 */
	public void setName(String name);

	/**
	 * Returns the email of this invitation info.
	 *
	 * @return the email of this invitation info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this invitation info.
	 *
	 * @param email the email of this invitation info
	 */
	public void setEmail(String email);

	/**
	 * Returns the description of this invitation info.
	 *
	 * @return the description of this invitation info
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this invitation info.
	 *
	 * @param description the description of this invitation info
	 */
	public void setDescription(String description);

	/**
	 * Returns the invited date of this invitation info.
	 *
	 * @return the invited date of this invitation info
	 */
	@AutoEscape
	public String getInvitedDate();

	/**
	 * Sets the invited date of this invitation info.
	 *
	 * @param invitedDate the invited date of this invitation info
	 */
	public void setInvitedDate(String invitedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.InvitationInfo invitationInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.InvitationInfo> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.InvitationInfo toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.InvitationInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}