/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rumbasolutions.flask.model.CampaignImages;
import com.rumbasolutions.flask.model.CampaignImagesModel;
import com.rumbasolutions.flask.model.CampaignImagesSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CampaignImages service. Represents a row in the &quot;flaskads_CampaignImages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rumbasolutions.flask.model.CampaignImagesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CampaignImagesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CampaignImagesImpl
 * @see com.rumbasolutions.flask.model.CampaignImages
 * @see com.rumbasolutions.flask.model.CampaignImagesModel
 * @generated
 */
@JSON(strict = true)
public class CampaignImagesModelImpl extends BaseModelImpl<CampaignImages>
	implements CampaignImagesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a campaign images model instance should use the {@link com.rumbasolutions.flask.model.CampaignImages} interface instead.
	 */
	public static final String TABLE_NAME = "flaskads_CampaignImages";
	public static final Object[][] TABLE_COLUMNS = {
			{ "campaignImageId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "imageTitle", Types.VARCHAR },
			{ "imageDesc", Types.VARCHAR },
			{ "imageUUID", Types.VARCHAR },
			{ "imageGroupId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table flaskads_CampaignImages (campaignImageId LONG not null primary key,userId LONG,createdDate DATE null,modifiedDate DATE null,imageTitle VARCHAR(75) null,imageDesc VARCHAR(75) null,imageUUID VARCHAR(75) null,imageGroupId LONG)";
	public static final String TABLE_SQL_DROP = "drop table flaskads_CampaignImages";
	public static final String ORDER_BY_JPQL = " ORDER BY campaignImages.campaignImageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY flaskads_CampaignImages.campaignImageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rumbasolutions.flask.model.CampaignImages"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rumbasolutions.flask.model.CampaignImages"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rumbasolutions.flask.model.CampaignImages"),
			true);
	public static long IMAGEUUID_COLUMN_BITMASK = 1L;
	public static long CAMPAIGNIMAGEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CampaignImages toModel(CampaignImagesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CampaignImages model = new CampaignImagesImpl();

		model.setCampaignImageId(soapModel.getCampaignImageId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setImageTitle(soapModel.getImageTitle());
		model.setImageDesc(soapModel.getImageDesc());
		model.setImageUUID(soapModel.getImageUUID());
		model.setImageGroupId(soapModel.getImageGroupId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CampaignImages> toModels(CampaignImagesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CampaignImages> models = new ArrayList<CampaignImages>(soapModels.length);

		for (CampaignImagesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rumbasolutions.flask.model.CampaignImages"));

	public CampaignImagesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _campaignImageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCampaignImageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _campaignImageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CampaignImages.class;
	}

	@Override
	public String getModelClassName() {
		return CampaignImages.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("campaignImageId", getCampaignImageId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("imageTitle", getImageTitle());
		attributes.put("imageDesc", getImageDesc());
		attributes.put("imageUUID", getImageUUID());
		attributes.put("imageGroupId", getImageGroupId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long campaignImageId = (Long)attributes.get("campaignImageId");

		if (campaignImageId != null) {
			setCampaignImageId(campaignImageId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String imageTitle = (String)attributes.get("imageTitle");

		if (imageTitle != null) {
			setImageTitle(imageTitle);
		}

		String imageDesc = (String)attributes.get("imageDesc");

		if (imageDesc != null) {
			setImageDesc(imageDesc);
		}

		String imageUUID = (String)attributes.get("imageUUID");

		if (imageUUID != null) {
			setImageUUID(imageUUID);
		}

		Long imageGroupId = (Long)attributes.get("imageGroupId");

		if (imageGroupId != null) {
			setImageGroupId(imageGroupId);
		}
	}

	@JSON
	@Override
	public long getCampaignImageId() {
		return _campaignImageId;
	}

	@Override
	public void setCampaignImageId(long campaignImageId) {
		_campaignImageId = campaignImageId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getImageTitle() {
		if (_imageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageTitle;
		}
	}

	@Override
	public void setImageTitle(String imageTitle) {
		_imageTitle = imageTitle;
	}

	@JSON
	@Override
	public String getImageDesc() {
		if (_imageDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageDesc;
		}
	}

	@Override
	public void setImageDesc(String imageDesc) {
		_imageDesc = imageDesc;
	}

	@JSON
	@Override
	public String getImageUUID() {
		if (_imageUUID == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUUID;
		}
	}

	@Override
	public void setImageUUID(String imageUUID) {
		_columnBitmask |= IMAGEUUID_COLUMN_BITMASK;

		if (_originalImageUUID == null) {
			_originalImageUUID = _imageUUID;
		}

		_imageUUID = imageUUID;
	}

	public String getOriginalImageUUID() {
		return GetterUtil.getString(_originalImageUUID);
	}

	@JSON
	@Override
	public long getImageGroupId() {
		return _imageGroupId;
	}

	@Override
	public void setImageGroupId(long imageGroupId) {
		_imageGroupId = imageGroupId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CampaignImages.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CampaignImages toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CampaignImages)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CampaignImagesImpl campaignImagesImpl = new CampaignImagesImpl();

		campaignImagesImpl.setCampaignImageId(getCampaignImageId());
		campaignImagesImpl.setUserId(getUserId());
		campaignImagesImpl.setCreatedDate(getCreatedDate());
		campaignImagesImpl.setModifiedDate(getModifiedDate());
		campaignImagesImpl.setImageTitle(getImageTitle());
		campaignImagesImpl.setImageDesc(getImageDesc());
		campaignImagesImpl.setImageUUID(getImageUUID());
		campaignImagesImpl.setImageGroupId(getImageGroupId());

		campaignImagesImpl.resetOriginalValues();

		return campaignImagesImpl;
	}

	@Override
	public int compareTo(CampaignImages campaignImages) {
		long primaryKey = campaignImages.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CampaignImages)) {
			return false;
		}

		CampaignImages campaignImages = (CampaignImages)obj;

		long primaryKey = campaignImages.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CampaignImagesModelImpl campaignImagesModelImpl = this;

		campaignImagesModelImpl._originalImageUUID = campaignImagesModelImpl._imageUUID;

		campaignImagesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CampaignImages> toCacheModel() {
		CampaignImagesCacheModel campaignImagesCacheModel = new CampaignImagesCacheModel();

		campaignImagesCacheModel.campaignImageId = getCampaignImageId();

		campaignImagesCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			campaignImagesCacheModel.createdDate = createdDate.getTime();
		}
		else {
			campaignImagesCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			campaignImagesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			campaignImagesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		campaignImagesCacheModel.imageTitle = getImageTitle();

		String imageTitle = campaignImagesCacheModel.imageTitle;

		if ((imageTitle != null) && (imageTitle.length() == 0)) {
			campaignImagesCacheModel.imageTitle = null;
		}

		campaignImagesCacheModel.imageDesc = getImageDesc();

		String imageDesc = campaignImagesCacheModel.imageDesc;

		if ((imageDesc != null) && (imageDesc.length() == 0)) {
			campaignImagesCacheModel.imageDesc = null;
		}

		campaignImagesCacheModel.imageUUID = getImageUUID();

		String imageUUID = campaignImagesCacheModel.imageUUID;

		if ((imageUUID != null) && (imageUUID.length() == 0)) {
			campaignImagesCacheModel.imageUUID = null;
		}

		campaignImagesCacheModel.imageGroupId = getImageGroupId();

		return campaignImagesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{campaignImageId=");
		sb.append(getCampaignImageId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", imageTitle=");
		sb.append(getImageTitle());
		sb.append(", imageDesc=");
		sb.append(getImageDesc());
		sb.append(", imageUUID=");
		sb.append(getImageUUID());
		sb.append(", imageGroupId=");
		sb.append(getImageGroupId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.rumbasolutions.flask.model.CampaignImages");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>campaignImageId</column-name><column-value><![CDATA[");
		sb.append(getCampaignImageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageTitle</column-name><column-value><![CDATA[");
		sb.append(getImageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageDesc</column-name><column-value><![CDATA[");
		sb.append(getImageDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUUID</column-name><column-value><![CDATA[");
		sb.append(getImageUUID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageGroupId</column-name><column-value><![CDATA[");
		sb.append(getImageGroupId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CampaignImages.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CampaignImages.class
		};
	private long _campaignImageId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private String _imageTitle;
	private String _imageDesc;
	private String _imageUUID;
	private String _originalImageUUID;
	private long _imageGroupId;
	private long _columnBitmask;
	private CampaignImages _escapedModel;
}