/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rumbasolutions.flask.model.CampaignImage;
import com.rumbasolutions.flask.model.CampaignImageModel;
import com.rumbasolutions.flask.model.CampaignImageSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CampaignImage service. Represents a row in the &quot;flaskads_CampaignImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rumbasolutions.flask.model.CampaignImageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CampaignImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CampaignImageImpl
 * @see com.rumbasolutions.flask.model.CampaignImage
 * @see com.rumbasolutions.flask.model.CampaignImageModel
 * @generated
 */
@JSON(strict = true)
public class CampaignImageModelImpl extends BaseModelImpl<CampaignImage>
	implements CampaignImageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a campaign image model instance should use the {@link com.rumbasolutions.flask.model.CampaignImage} interface instead.
	 */
	public static final String TABLE_NAME = "flaskads_CampaignImage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "campaignImageId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createdDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "imageTitle", Types.VARCHAR },
			{ "imageDesc", Types.VARCHAR },
			{ "imageUUID", Types.VARCHAR },
			{ "imageGroupId", Types.BIGINT },
			{ "campaignId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table flaskads_CampaignImage (campaignImageId LONG not null primary key,userId LONG,createdDate DATE null,modifiedDate DATE null,imageTitle VARCHAR(100) null,imageDesc VARCHAR(255) null,imageUUID VARCHAR(75) null,imageGroupId LONG,campaignId LONG)";
	public static final String TABLE_SQL_DROP = "drop table flaskads_CampaignImage";
	public static final String ORDER_BY_JPQL = " ORDER BY campaignImage.campaignImageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY flaskads_CampaignImage.campaignImageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rumbasolutions.flask.model.CampaignImage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rumbasolutions.flask.model.CampaignImage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rumbasolutions.flask.model.CampaignImage"),
			true);
	public static long CAMPAIGNID_COLUMN_BITMASK = 1L;
	public static long IMAGEUUID_COLUMN_BITMASK = 2L;
	public static long CAMPAIGNIMAGEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CampaignImage toModel(CampaignImageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CampaignImage model = new CampaignImageImpl();

		model.setCampaignImageId(soapModel.getCampaignImageId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setImageTitle(soapModel.getImageTitle());
		model.setImageDesc(soapModel.getImageDesc());
		model.setImageUUID(soapModel.getImageUUID());
		model.setImageGroupId(soapModel.getImageGroupId());
		model.setCampaignId(soapModel.getCampaignId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CampaignImage> toModels(CampaignImageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CampaignImage> models = new ArrayList<CampaignImage>(soapModels.length);

		for (CampaignImageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rumbasolutions.flask.model.CampaignImage"));

	public CampaignImageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _campaignImageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCampaignImageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _campaignImageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CampaignImage.class;
	}

	@Override
	public String getModelClassName() {
		return CampaignImage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("campaignImageId", getCampaignImageId());
		attributes.put("userId", getUserId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("imageTitle", getImageTitle());
		attributes.put("imageDesc", getImageDesc());
		attributes.put("imageUUID", getImageUUID());
		attributes.put("imageGroupId", getImageGroupId());
		attributes.put("campaignId", getCampaignId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long campaignImageId = (Long)attributes.get("campaignImageId");

		if (campaignImageId != null) {
			setCampaignImageId(campaignImageId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String imageTitle = (String)attributes.get("imageTitle");

		if (imageTitle != null) {
			setImageTitle(imageTitle);
		}

		String imageDesc = (String)attributes.get("imageDesc");

		if (imageDesc != null) {
			setImageDesc(imageDesc);
		}

		String imageUUID = (String)attributes.get("imageUUID");

		if (imageUUID != null) {
			setImageUUID(imageUUID);
		}

		Long imageGroupId = (Long)attributes.get("imageGroupId");

		if (imageGroupId != null) {
			setImageGroupId(imageGroupId);
		}

		Long campaignId = (Long)attributes.get("campaignId");

		if (campaignId != null) {
			setCampaignId(campaignId);
		}
	}

	@JSON
	@Override
	public long getCampaignImageId() {
		return _campaignImageId;
	}

	@Override
	public void setCampaignImageId(long campaignImageId) {
		_campaignImageId = campaignImageId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getImageTitle() {
		if (_imageTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageTitle;
		}
	}

	@Override
	public void setImageTitle(String imageTitle) {
		_imageTitle = imageTitle;
	}

	@JSON
	@Override
	public String getImageDesc() {
		if (_imageDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageDesc;
		}
	}

	@Override
	public void setImageDesc(String imageDesc) {
		_imageDesc = imageDesc;
	}

	@JSON
	@Override
	public String getImageUUID() {
		if (_imageUUID == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageUUID;
		}
	}

	@Override
	public void setImageUUID(String imageUUID) {
		_columnBitmask |= IMAGEUUID_COLUMN_BITMASK;

		if (_originalImageUUID == null) {
			_originalImageUUID = _imageUUID;
		}

		_imageUUID = imageUUID;
	}

	public String getOriginalImageUUID() {
		return GetterUtil.getString(_originalImageUUID);
	}

	@JSON
	@Override
	public long getImageGroupId() {
		return _imageGroupId;
	}

	@Override
	public void setImageGroupId(long imageGroupId) {
		_imageGroupId = imageGroupId;
	}

	@JSON
	@Override
	public long getCampaignId() {
		return _campaignId;
	}

	@Override
	public void setCampaignId(long campaignId) {
		_columnBitmask |= CAMPAIGNID_COLUMN_BITMASK;

		if (!_setOriginalCampaignId) {
			_setOriginalCampaignId = true;

			_originalCampaignId = _campaignId;
		}

		_campaignId = campaignId;
	}

	public long getOriginalCampaignId() {
		return _originalCampaignId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CampaignImage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CampaignImage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CampaignImage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CampaignImageImpl campaignImageImpl = new CampaignImageImpl();

		campaignImageImpl.setCampaignImageId(getCampaignImageId());
		campaignImageImpl.setUserId(getUserId());
		campaignImageImpl.setCreatedDate(getCreatedDate());
		campaignImageImpl.setModifiedDate(getModifiedDate());
		campaignImageImpl.setImageTitle(getImageTitle());
		campaignImageImpl.setImageDesc(getImageDesc());
		campaignImageImpl.setImageUUID(getImageUUID());
		campaignImageImpl.setImageGroupId(getImageGroupId());
		campaignImageImpl.setCampaignId(getCampaignId());

		campaignImageImpl.resetOriginalValues();

		return campaignImageImpl;
	}

	@Override
	public int compareTo(CampaignImage campaignImage) {
		long primaryKey = campaignImage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CampaignImage)) {
			return false;
		}

		CampaignImage campaignImage = (CampaignImage)obj;

		long primaryKey = campaignImage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CampaignImageModelImpl campaignImageModelImpl = this;

		campaignImageModelImpl._originalImageUUID = campaignImageModelImpl._imageUUID;

		campaignImageModelImpl._originalCampaignId = campaignImageModelImpl._campaignId;

		campaignImageModelImpl._setOriginalCampaignId = false;

		campaignImageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CampaignImage> toCacheModel() {
		CampaignImageCacheModel campaignImageCacheModel = new CampaignImageCacheModel();

		campaignImageCacheModel.campaignImageId = getCampaignImageId();

		campaignImageCacheModel.userId = getUserId();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			campaignImageCacheModel.createdDate = createdDate.getTime();
		}
		else {
			campaignImageCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			campaignImageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			campaignImageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		campaignImageCacheModel.imageTitle = getImageTitle();

		String imageTitle = campaignImageCacheModel.imageTitle;

		if ((imageTitle != null) && (imageTitle.length() == 0)) {
			campaignImageCacheModel.imageTitle = null;
		}

		campaignImageCacheModel.imageDesc = getImageDesc();

		String imageDesc = campaignImageCacheModel.imageDesc;

		if ((imageDesc != null) && (imageDesc.length() == 0)) {
			campaignImageCacheModel.imageDesc = null;
		}

		campaignImageCacheModel.imageUUID = getImageUUID();

		String imageUUID = campaignImageCacheModel.imageUUID;

		if ((imageUUID != null) && (imageUUID.length() == 0)) {
			campaignImageCacheModel.imageUUID = null;
		}

		campaignImageCacheModel.imageGroupId = getImageGroupId();

		campaignImageCacheModel.campaignId = getCampaignId();

		return campaignImageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{campaignImageId=");
		sb.append(getCampaignImageId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", imageTitle=");
		sb.append(getImageTitle());
		sb.append(", imageDesc=");
		sb.append(getImageDesc());
		sb.append(", imageUUID=");
		sb.append(getImageUUID());
		sb.append(", imageGroupId=");
		sb.append(getImageGroupId());
		sb.append(", campaignId=");
		sb.append(getCampaignId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rumbasolutions.flask.model.CampaignImage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>campaignImageId</column-name><column-value><![CDATA[");
		sb.append(getCampaignImageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageTitle</column-name><column-value><![CDATA[");
		sb.append(getImageTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageDesc</column-name><column-value><![CDATA[");
		sb.append(getImageDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageUUID</column-name><column-value><![CDATA[");
		sb.append(getImageUUID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageGroupId</column-name><column-value><![CDATA[");
		sb.append(getImageGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>campaignId</column-name><column-value><![CDATA[");
		sb.append(getCampaignId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CampaignImage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CampaignImage.class
		};
	private long _campaignImageId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private String _imageTitle;
	private String _imageDesc;
	private String _imageUUID;
	private String _originalImageUUID;
	private long _imageGroupId;
	private long _campaignId;
	private long _originalCampaignId;
	private boolean _setOriginalCampaignId;
	private long _columnBitmask;
	private CampaignImage _escapedModel;
}