/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FlaskRole service. Represents a row in the &quot;flaskusers_FlaskRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.FlaskRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.FlaskRoleImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see FlaskRole
 * @see com.rumbasolutions.flask.model.impl.FlaskRoleImpl
 * @see com.rumbasolutions.flask.model.impl.FlaskRoleModelImpl
 * @generated
 */
public interface FlaskRoleModel extends BaseModel<FlaskRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flask role model instance should use the {@link FlaskRole} interface instead.
	 */

	/**
	 * Returns the primary key of this flask role.
	 *
	 * @return the primary key of this flask role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flask role.
	 *
	 * @param primaryKey the primary key of this flask role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the role ID of this flask role.
	 *
	 * @return the role ID of this flask role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this flask role.
	 *
	 * @param roleId the role ID of this flask role
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the role name of this flask role.
	 *
	 * @return the role name of this flask role
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this flask role.
	 *
	 * @param roleName the role name of this flask role
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the role desc of this flask role.
	 *
	 * @return the role desc of this flask role
	 */
	@AutoEscape
	public String getRoleDesc();

	/**
	 * Sets the role desc of this flask role.
	 *
	 * @param roleDesc the role desc of this flask role
	 */
	public void setRoleDesc(String roleDesc);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.FlaskRole flaskRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.FlaskRole> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.FlaskRole toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.FlaskRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}