/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FlaskUser service. Represents a row in the &quot;flaskusers_FlaskUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.FlaskUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.FlaskUserImpl}.
 * </p>
 *
 * @author Ashutosh Rai
 * @see FlaskUser
 * @see com.rumbasolutions.flask.model.impl.FlaskUserImpl
 * @see com.rumbasolutions.flask.model.impl.FlaskUserModelImpl
 * @generated
 */
public interface FlaskUserModel extends BaseModel<FlaskUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flask user model instance should use the {@link FlaskUser} interface instead.
	 */

	/**
	 * Returns the primary key of this flask user.
	 *
	 * @return the primary key of this flask user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flask user.
	 *
	 * @param primaryKey the primary key of this flask user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this flask user.
	 *
	 * @return the user ID of this flask user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this flask user.
	 *
	 * @param userId the user ID of this flask user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this flask user.
	 *
	 * @return the user uuid of this flask user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this flask user.
	 *
	 * @param userUuid the user uuid of this flask user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the role ID of this flask user.
	 *
	 * @return the role ID of this flask user
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this flask user.
	 *
	 * @param roleId the role ID of this flask user
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the first name of this flask user.
	 *
	 * @return the first name of this flask user
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this flask user.
	 *
	 * @param firstName the first name of this flask user
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the middle name of this flask user.
	 *
	 * @return the middle name of this flask user
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this flask user.
	 *
	 * @param middleName the middle name of this flask user
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the last name of this flask user.
	 *
	 * @return the last name of this flask user
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this flask user.
	 *
	 * @param lastName the last name of this flask user
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the screen name of this flask user.
	 *
	 * @return the screen name of this flask user
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this flask user.
	 *
	 * @param screenName the screen name of this flask user
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the email of this flask user.
	 *
	 * @return the email of this flask user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this flask user.
	 *
	 * @param email the email of this flask user
	 */
	public void setEmail(String email);

	/**
	 * Returns the d o b of this flask user.
	 *
	 * @return the d o b of this flask user
	 */
	public Date getDOB();

	/**
	 * Sets the d o b of this flask user.
	 *
	 * @param DOB the d o b of this flask user
	 */
	public void setDOB(Date DOB);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.FlaskUser flaskUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.FlaskUser> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.FlaskUser toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.FlaskUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}