/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdCustomer service. Represents a row in the &quot;flaskads_AdCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.AdCustomerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.AdCustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdCustomer
 * @see com.rumbasolutions.flask.model.impl.AdCustomerImpl
 * @see com.rumbasolutions.flask.model.impl.AdCustomerModelImpl
 * @generated
 */
public interface AdCustomerModel extends BaseModel<AdCustomer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ad customer model instance should use the {@link AdCustomer} interface instead.
	 */

	/**
	 * Returns the primary key of this ad customer.
	 *
	 * @return the primary key of this ad customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ad customer.
	 *
	 * @param primaryKey the primary key of this ad customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the customer ID of this ad customer.
	 *
	 * @return the customer ID of this ad customer
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this ad customer.
	 *
	 * @param customerId the customer ID of this ad customer
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the user ID of this ad customer.
	 *
	 * @return the user ID of this ad customer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ad customer.
	 *
	 * @param userId the user ID of this ad customer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ad customer.
	 *
	 * @return the user uuid of this ad customer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ad customer.
	 *
	 * @param userUuid the user uuid of this ad customer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this ad customer.
	 *
	 * @return the created date of this ad customer
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this ad customer.
	 *
	 * @param createdDate the created date of this ad customer
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this ad customer.
	 *
	 * @return the modified date of this ad customer
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ad customer.
	 *
	 * @param modifiedDate the modified date of this ad customer
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the customer name of this ad customer.
	 *
	 * @return the customer name of this ad customer
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this ad customer.
	 *
	 * @param customerName the customer name of this ad customer
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the business type of this ad customer.
	 *
	 * @return the business type of this ad customer
	 */
	@AutoEscape
	public String getBusinessType();

	/**
	 * Sets the business type of this ad customer.
	 *
	 * @param businessType the business type of this ad customer
	 */
	public void setBusinessType(String businessType);

	/**
	 * Returns the addr line1 of this ad customer.
	 *
	 * @return the addr line1 of this ad customer
	 */
	@AutoEscape
	public String getAddrLine1();

	/**
	 * Sets the addr line1 of this ad customer.
	 *
	 * @param addrLine1 the addr line1 of this ad customer
	 */
	public void setAddrLine1(String addrLine1);

	/**
	 * Returns the addr line2 of this ad customer.
	 *
	 * @return the addr line2 of this ad customer
	 */
	@AutoEscape
	public String getAddrLine2();

	/**
	 * Sets the addr line2 of this ad customer.
	 *
	 * @param addrLine2 the addr line2 of this ad customer
	 */
	public void setAddrLine2(String addrLine2);

	/**
	 * Returns the city of this ad customer.
	 *
	 * @return the city of this ad customer
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this ad customer.
	 *
	 * @param city the city of this ad customer
	 */
	public void setCity(String city);

	/**
	 * Returns the zip code of this ad customer.
	 *
	 * @return the zip code of this ad customer
	 */
	@AutoEscape
	public String getZipCode();

	/**
	 * Sets the zip code of this ad customer.
	 *
	 * @param zipCode the zip code of this ad customer
	 */
	public void setZipCode(String zipCode);

	/**
	 * Returns the state ID of this ad customer.
	 *
	 * @return the state ID of this ad customer
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this ad customer.
	 *
	 * @param stateId the state ID of this ad customer
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the country ID of this ad customer.
	 *
	 * @return the country ID of this ad customer
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this ad customer.
	 *
	 * @param countryId the country ID of this ad customer
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the email of this ad customer.
	 *
	 * @return the email of this ad customer
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this ad customer.
	 *
	 * @param email the email of this ad customer
	 */
	public void setEmail(String email);

	/**
	 * Returns the website u r l of this ad customer.
	 *
	 * @return the website u r l of this ad customer
	 */
	@AutoEscape
	public String getWebsiteURL();

	/**
	 * Sets the website u r l of this ad customer.
	 *
	 * @param websiteURL the website u r l of this ad customer
	 */
	public void setWebsiteURL(String websiteURL);

	/**
	 * Returns the business phone number of this ad customer.
	 *
	 * @return the business phone number of this ad customer
	 */
	@AutoEscape
	public String getBusinessPhoneNumber();

	/**
	 * Sets the business phone number of this ad customer.
	 *
	 * @param businessPhoneNumber the business phone number of this ad customer
	 */
	public void setBusinessPhoneNumber(String businessPhoneNumber);

	/**
	 * Returns the contact person name of this ad customer.
	 *
	 * @return the contact person name of this ad customer
	 */
	@AutoEscape
	public String getContactPersonName();

	/**
	 * Sets the contact person name of this ad customer.
	 *
	 * @param contactPersonName the contact person name of this ad customer
	 */
	public void setContactPersonName(String contactPersonName);

	/**
	 * Returns the contact person number of this ad customer.
	 *
	 * @return the contact person number of this ad customer
	 */
	@AutoEscape
	public String getContactPersonNumber();

	/**
	 * Sets the contact person number of this ad customer.
	 *
	 * @param contactPersonNumber the contact person number of this ad customer
	 */
	public void setContactPersonNumber(String contactPersonNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rumbasolutions.flask.model.AdCustomer adCustomer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.AdCustomer> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.AdCustomer toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.AdCustomer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}