/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rumbasolutions.flask.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CampaignImage service. Represents a row in the &quot;flaskads_CampaignImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rumbasolutions.flask.model.impl.CampaignImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rumbasolutions.flask.model.impl.CampaignImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CampaignImage
 * @see com.rumbasolutions.flask.model.impl.CampaignImageImpl
 * @see com.rumbasolutions.flask.model.impl.CampaignImageModelImpl
 * @generated
 */
public interface CampaignImageModel extends BaseModel<CampaignImage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a campaign image model instance should use the {@link CampaignImage} interface instead.
	 */

	/**
	 * Returns the primary key of this campaign image.
	 *
	 * @return the primary key of this campaign image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this campaign image.
	 *
	 * @param primaryKey the primary key of this campaign image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the campaign image ID of this campaign image.
	 *
	 * @return the campaign image ID of this campaign image
	 */
	public long getCampaignImageId();

	/**
	 * Sets the campaign image ID of this campaign image.
	 *
	 * @param campaignImageId the campaign image ID of this campaign image
	 */
	public void setCampaignImageId(long campaignImageId);

	/**
	 * Returns the user ID of this campaign image.
	 *
	 * @return the user ID of this campaign image
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this campaign image.
	 *
	 * @param userId the user ID of this campaign image
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this campaign image.
	 *
	 * @return the user uuid of this campaign image
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this campaign image.
	 *
	 * @param userUuid the user uuid of this campaign image
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the created date of this campaign image.
	 *
	 * @return the created date of this campaign image
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this campaign image.
	 *
	 * @param createdDate the created date of this campaign image
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this campaign image.
	 *
	 * @return the modified date of this campaign image
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this campaign image.
	 *
	 * @param modifiedDate the modified date of this campaign image
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the image title of this campaign image.
	 *
	 * @return the image title of this campaign image
	 */
	@AutoEscape
	public String getImageTitle();

	/**
	 * Sets the image title of this campaign image.
	 *
	 * @param imageTitle the image title of this campaign image
	 */
	public void setImageTitle(String imageTitle);

	/**
	 * Returns the image desc of this campaign image.
	 *
	 * @return the image desc of this campaign image
	 */
	@AutoEscape
	public String getImageDesc();

	/**
	 * Sets the image desc of this campaign image.
	 *
	 * @param imageDesc the image desc of this campaign image
	 */
	public void setImageDesc(String imageDesc);

	/**
	 * Returns the image u u i d of this campaign image.
	 *
	 * @return the image u u i d of this campaign image
	 */
	@AutoEscape
	public String getImageUUID();

	/**
	 * Sets the image u u i d of this campaign image.
	 *
	 * @param imageUUID the image u u i d of this campaign image
	 */
	public void setImageUUID(String imageUUID);

	/**
	 * Returns the image group ID of this campaign image.
	 *
	 * @return the image group ID of this campaign image
	 */
	public long getImageGroupId();

	/**
	 * Sets the image group ID of this campaign image.
	 *
	 * @param imageGroupId the image group ID of this campaign image
	 */
	public void setImageGroupId(long imageGroupId);

	/**
	 * Returns the campaign ID of this campaign image.
	 *
	 * @return the campaign ID of this campaign image
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this campaign image.
	 *
	 * @param campaignId the campaign ID of this campaign image
	 */
	public void setCampaignId(long campaignId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rumbasolutions.flask.model.CampaignImage campaignImage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rumbasolutions.flask.model.CampaignImage> toCacheModel();

	@Override
	public com.rumbasolutions.flask.model.CampaignImage toEscapedModel();

	@Override
	public com.rumbasolutions.flask.model.CampaignImage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}