/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.contacts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DeviceAwsEndpoint service. Represents a row in the &quot;Contacts_DeviceAwsEndpoint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.contacts.model.impl.DeviceAwsEndpointModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.contacts.model.impl.DeviceAwsEndpointImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DeviceAwsEndpoint
 * @see com.liferay.contacts.model.impl.DeviceAwsEndpointImpl
 * @see com.liferay.contacts.model.impl.DeviceAwsEndpointModelImpl
 * @generated
 */
public interface DeviceAwsEndpointModel extends BaseModel<DeviceAwsEndpoint> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a device aws endpoint model instance should use the {@link DeviceAwsEndpoint} interface instead.
	 */

	/**
	 * Returns the primary key of this device aws endpoint.
	 *
	 * @return the primary key of this device aws endpoint
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this device aws endpoint.
	 *
	 * @param primaryKey the primary key of this device aws endpoint
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the device end point ID of this device aws endpoint.
	 *
	 * @return the device end point ID of this device aws endpoint
	 */
	public long getDeviceEndPointId();

	/**
	 * Sets the device end point ID of this device aws endpoint.
	 *
	 * @param deviceEndPointId the device end point ID of this device aws endpoint
	 */
	public void setDeviceEndPointId(long deviceEndPointId);

	/**
	 * Returns the aws endpoint of this device aws endpoint.
	 *
	 * @return the aws endpoint of this device aws endpoint
	 */
	@AutoEscape
	public String getAwsEndpoint();

	/**
	 * Sets the aws endpoint of this device aws endpoint.
	 *
	 * @param awsEndpoint the aws endpoint of this device aws endpoint
	 */
	public void setAwsEndpoint(String awsEndpoint);

	/**
	 * Returns the user device registration ID of this device aws endpoint.
	 *
	 * @return the user device registration ID of this device aws endpoint
	 */
	public long getUserDeviceRegistrationId();

	/**
	 * Sets the user device registration ID of this device aws endpoint.
	 *
	 * @param userDeviceRegistrationId the user device registration ID of this device aws endpoint
	 */
	public void setUserDeviceRegistrationId(long userDeviceRegistrationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.contacts.model.DeviceAwsEndpoint deviceAwsEndpoint);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.contacts.model.DeviceAwsEndpoint> toCacheModel();

	@Override
	public com.liferay.contacts.model.DeviceAwsEndpoint toEscapedModel();

	@Override
	public com.liferay.contacts.model.DeviceAwsEndpoint toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}