/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.contacts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FlaskGroupRecipients service. Represents a row in the &quot;Contacts_FlaskGroupRecipients&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.contacts.model.impl.FlaskGroupRecipientsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.contacts.model.impl.FlaskGroupRecipientsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FlaskGroupRecipients
 * @see com.liferay.contacts.model.impl.FlaskGroupRecipientsImpl
 * @see com.liferay.contacts.model.impl.FlaskGroupRecipientsModelImpl
 * @generated
 */
public interface FlaskGroupRecipientsModel extends BaseModel<FlaskGroupRecipients> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flask group recipients model instance should use the {@link FlaskGroupRecipients} interface instead.
	 */

	/**
	 * Returns the primary key of this flask group recipients.
	 *
	 * @return the primary key of this flask group recipients
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flask group recipients.
	 *
	 * @param primaryKey the primary key of this flask group recipients
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group recipient ID of this flask group recipients.
	 *
	 * @return the group recipient ID of this flask group recipients
	 */
	public long getGroupRecipientId();

	/**
	 * Sets the group recipient ID of this flask group recipients.
	 *
	 * @param groupRecipientId the group recipient ID of this flask group recipients
	 */
	public void setGroupRecipientId(long groupRecipientId);

	/**
	 * Returns the group ID of this flask group recipients.
	 *
	 * @return the group ID of this flask group recipients
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this flask group recipients.
	 *
	 * @param groupId the group ID of this flask group recipients
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the recipients of this flask group recipients.
	 *
	 * @return the recipients of this flask group recipients
	 */
	@AutoEscape
	public String getRecipients();

	/**
	 * Sets the recipients of this flask group recipients.
	 *
	 * @param recipients the recipients of this flask group recipients
	 */
	public void setRecipients(String recipients);

	/**
	 * Returns the group message ID of this flask group recipients.
	 *
	 * @return the group message ID of this flask group recipients
	 */
	public long getGroupMessageId();

	/**
	 * Sets the group message ID of this flask group recipients.
	 *
	 * @param groupMessageId the group message ID of this flask group recipients
	 */
	public void setGroupMessageId(long groupMessageId);

	/**
	 * Returns the read of this flask group recipients.
	 *
	 * @return the read of this flask group recipients
	 */
	@AutoEscape
	public String getRead();

	/**
	 * Sets the read of this flask group recipients.
	 *
	 * @param read the read of this flask group recipients
	 */
	public void setRead(String read);

	/**
	 * Returns the received date time of this flask group recipients.
	 *
	 * @return the received date time of this flask group recipients
	 */
	public Date getReceivedDateTime();

	/**
	 * Sets the received date time of this flask group recipients.
	 *
	 * @param receivedDateTime the received date time of this flask group recipients
	 */
	public void setReceivedDateTime(Date receivedDateTime);

	/**
	 * Returns the sender ID of this flask group recipients.
	 *
	 * @return the sender ID of this flask group recipients
	 */
	public long getSenderId();

	/**
	 * Sets the sender ID of this flask group recipients.
	 *
	 * @param senderId the sender ID of this flask group recipients
	 */
	public void setSenderId(long senderId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.contacts.model.FlaskGroupRecipients flaskGroupRecipients);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.contacts.model.FlaskGroupRecipients> toCacheModel();

	@Override
	public com.liferay.contacts.model.FlaskGroupRecipients toEscapedModel();

	@Override
	public com.liferay.contacts.model.FlaskGroupRecipients toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}